### ISSUE TITLE
Babel plugin for circular dependencies

### ISSUE THREAD

**Issue by TylorS** [cyclejs/core#170]
As per discussion, sometimes the way that dialogues are developed can introduce an awkward feedback loop.

Per @staltz' example
```javascript
  const proxyTextFilterSinks = {value$: new Rx.Subject()};
  const actions = intent(proxyTextFilterSinks);
  const state$ = model(peoplePageHTTP.response$, sources.props$, actions);
  const textFilter = TextFilterWrapper(state$, sources.DOM);
  replicateStream(textFilter.value$, proxyTextFilterSinks.value$);
```

The development of a babel plugin could potentially ease this pain, and doesn't require the writing of an entirely new language.

**Comment by TylorS** [comment]
Links of potential Interest

https://babeljs.io/docs/advanced/plugins/
http://babeljs.io/docs/advanced/plugins/visiting/
http://babeljs.io/docs/advanced/plugins/manipulation/
http://babeljs.io/docs/advanced/plugins/scope/

**Comment by TylorS** [comment]
Maybe a set of macros could be used?

https://github.com/codemix/babel-plugin-macros

**Comment by staltz** [comment]
Maybe, but they aren't the best API possible. The best one is simply writing down the circular dependency and then the plugin magically sorts things out.

**Comment by TylorS** [comment]
I'm just thinking out load. Been investigating babel plugins, they aren't documented very well. Had a bit of trouble just making just a simple example plugin. However it is very powerful and I'm sure that just about anything can be done.

**Comment by staltz** [comment]
Yes, ideas are welcomed :+1:

**Comment by TylorS** [comment]
I'm wondering about how this babel plugin would work. 
Initial thoughts:

1. Identifier contains '$' as a suffix (or prefix? or both?)
2. Identifier 'X$' is referenced but is not defined in scope yet. If it is continue and go back to step 1.
3. Store a reference of this? (Not sure about this)
4. If never defined let Babel do it's normal error handling, otherwise we need to create a proxy object 'proxyX$'.
5. Insert 'proxyX$' just before the X$ is referenced.
6. Change initial 'X$' reference to 'proxyX$'
7.  call `replicateStream(X$, proxyX$)`

**Comment by staltz** [comment]
Sounds like a good draft :+1:

**Comment by TylorS** [comment]
I see one initial problem, which is the `replicateStream()` function, is where it is defined and how we would access it. There are 3 options that I see currently.

1. The plugin defines it globally. `window.replicateStream()`
    - What if the user already has this defined somewhere for some reason?
2. The plugin defines it locally, but it would have to be done so multiple times,
3. The user must provide it somehow, and it would have to have a certain name.

Personally I would lean towards 2.
Babel provides the `scope.generateUidIdentifier()` method to create a unique identifier that doesn't collide with any other declared in scope.

**Comment by staltz** [comment]
You forgot option 4:

- Just call `X$.subscribe(proxyX$.asObserver())` instead of `replicateStream`

That's what replicateStream does. The only reason why I made it a function is to keep the level of abstraction neat, because that subscribe with asObserver inside doesn't tell you what is the purpose. `replicateStream` works just as a comment.

**Comment by TylorS** [comment]
Perfect! :+1:

**Comment by staltz** [comment]
By the way, beware of this issue I just filed https://github.com/Reactive-Extensions/RxJS/issues/934

**Comment by TylorS** [comment]
Will do!

**Comment by TylorS** [comment]
After some trial and error, I've come to the conclusion that this might not be possible, or maybe there are features which I have not found yet to facilitate this sort of thing. 

I've be able to accomplish this 
- Find identifier `$$x` (prefixed with $$, to be replaced with proxy) 
- See if the same identifier minus one $ `$x` exists in scope (prefixed with $, to be proxied). 
-- I went with this route since the plugin API doesn't distinguish **when** it is declared in scope
- Declare `proxy$x` (without being assigned a value) at top of scope, and rename the identifier `$$x` to `proxy$x` 

This is as far as I have been able to get. The reason I don't see this being possible (yet), is that there is no way to inspect what will be assigned to `$x` to be able to properly proxy them. I don't think it would be fair to just assume `$x` itself needs to be proxied 100% of the time, but will often be `$x.someValue` or potentially multiple properties of `$x` that need to be proxied.

If anyone has ideas how to solve this, I'd love to hear it.

**Comment by TylorS** [comment]
With version 6.0.0 of Babel released, plugins can now tap into the parser. This may now be possible

**Comment by staltz** [comment]
Yay!

**Comment by Frikki** [comment]
Could someone elaborate why this proxy is needed in the first place?

**Comment by staltz** [comment]
To make circularly dependent observables.

**Comment by TylorS** [comment]
https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md
The babel-plugin handbook has been updated with information on writing plugins

**Comment by staltz** [comment]
Yep, that's a great guide.

**Comment by whitecolor** [comment]
Why in:
```
  replicateStream(origin$, proxy$) {
    origin$.subscribe(proxy$.asObserver());
  }
```
`.asObserver()` is used? what does it give?

@TylorS 
An the second question
How this code:
```
  const proxyTextFilterSinks = {value$: new Rx.Subject()};
  const actions = intent(proxyTextFilterSinks);
  const state$ = model(peoplePageHTTP.response$, sources.props$, actions);
  const textFilter = TextFilterWrapper(state$, sources.DOM);
  replicateStream(textFilter.value$, proxyTextFilterSinks.value$);
```
would look like with such plugin?
```
  const actions = intent({value$: tesxtFilter.value$});
  const state$ = model(peoplePageHTTP.response$, sources.props$, actions);
  const textFilter = TextFilterWrapper(state$, sources.DOM);
```
This looks like a real implicit hack.

**Comment by staltz** [comment]
> .asObserver() is used? what does it give?

It's not necessary, we could remove it. And we are, when rewriting Cycle in TypeScript.

> This looks like a real implicit hack. Not a cycle explicit way imo.

It's all explicit, it just isn't anymore ordered. The idea with this plugin is to eliminate the need for declaring things from top to bottom. As long as all pieces are eventually declared, it works.

I know it's not the JavaScript way, but that's why it's a babel plugin.

**Comment by whitecolor** [comment]
ok, I was able for now to implement babel plugin that uses global `curcular` callee as marker for cicular dependecy, so it can turn this:
```
function x() {
  var actions = intent({ value$: circular(textFilter.value$)});
  var state$ = model(peoplePageHTTP.response$, sources.props$, actions);
  var textFilter = TextFilterWrapper(state$, sources.DOM);
}

into this:
```
function x() {
  const textFilter_value$__Proxy = new Rx.Subject();

  var actions = intent({ value$: textFilter_value$__Proxy });
  var state$ = model(peoplePageHTTP.response$, sources.props$, actions);
  var textFilter = TextFilterWrapper(state$, sources.DOM);

  textFilter.value$.subscribe(textFilter_value$__Proxy.asObserver())
}
```
It finds `curcular` expression call replaces it with proxy, adds proxy declaration at the beginning, and subscription at the end of the function.

Wdt about such approach?

**Comment by staltz** [comment]
Good that it works! I would still try to brainstorm around the name for `circular`, or whether to use it at all. How bad would it be for readability if we wouldn't write `circular()` but the plugin would detect on its own?

**Comment by whitecolor** [comment]
I have to investigate futher to find out the possible (and better) way how to make it without special "keyword". 

What about using `Subject` vs `ReplaySubject(1)`?

BTW what you thinkg about modules written in TypeScript on that matter?

**Comment by staltz** [comment]
An alternative for the babel plugin would be a sweet.js macro: http://sweetjs.org/ (PS: sweet.js is now 1.0)

**Comment by whitecolor** [comment]
sweet will require some macro keyword i believe. 
I actuall figured out how it can be done with `babel-plugin` without need of keyword, by finding references used before declarations.

**Comment by whitecolor** [comment]
here is a draft https://github.com/whitecolor/babel-plugin-cycle-circular

**Comment by TylorS** [comment]
Great work @whitecolor :+1:

**Comment by TylorS** [comment]
I'm curious as to when and how I would make use of the options `identifiers`, `include`, and `exclude`?

**Comment by staltz** [comment]
Great stuff @whitecolor ! We could already start taking this into use, to experiment with it and make sure it's solid to use.

If anyone else is reading this and has used the plugin successfully, please let us know.

Also, the next step would be allowing options to specify different stream libraries, since soon we'll be supporting RxJS 5, most.js, etc.

**Comment by whitecolor** [comment]
I haven't published in on NPM yet (you can try from git) and it requires `Subject` or `Rx` to imported in the file, I will add this soon.

> I'm curious as to when and how I would make use of the options identifiers, include, and exclude?

1) for example if you want to handle only ids that contain $ at the end `componet.value$` you do identifieer: '\\$$' (string RegExp)
2) indlude, exclude if you want not all files in the project to be handled by plugin, maybe want to exlude folders with non-cycle stuff - not nesessary

There is a certain "questions" that need to be resolved:
1. Define solid procedure fo subject creation: can we just use `new Subject()`, or there might be cases where `ReplaySubject` or `BehaviourSubject` is needed?
2. Define unsubsribe from subject techinique (getting rid of leak).
3. How reference to `Subject` should be imported 
  - we may check if reference is present, 
  - if not we may insert `import` (require) in the beginning of the file
  - we may also just insert require (`const Subject = require('rx').Subject`) in the beginning of the scope (function)
4. The same should be done for other libs rxjs5, most, etc
5. yes there will be option for default lib is used and it can be per-folder basis using in-folder `.babelrc` (if different libs are used in project)
6. Is there a need is some more strict default convetions for example handle only functions that start with capital letter, or handle ony idenifier that contain `$` at the end.
7. There is aslo may be cases when applying proxy is not correct (if var is declared after usage but it is not a stream) - in this case code either will be broken pugin, or we actually can handle this situation for every case (check if `typeof targetIdentifier.subsribe === 'function'`) but it will make resulting code more bulky (but more safe).

**Comment by staltz** [comment]
> 1. Define solid procedure fo subject creation: can we just use new Subject(), or there might be cases where ReplaySubject or BehaviourSubject is needed?

I *think* we can use just Subject. The proxy Subject is anyway just doing what the real stream does. So the real stream could have e.g. `.shareReplay(1)` at the end of its definition, and the proxy will imitate that. 

> 2. Define unsubsribe from subject techinique (getting rid of leak).

I think we just need to make sure that components that will disappear should not have infinite streams. We can convert from infinite to finite using `takeUntil`.

> we may check if reference is present,
> if not we may insert import (require) in the beginning of the file

Sounds correct.

> There is aslo may be cases when applying proxy is not correct (if var is declared after usage but it is not a stream) - in this case code either will be broken pugin, or we actually can handle this situation for every case (check if typeof targetIdentifier.subsribe === 'function') but it will make resulting code more bulky (but more safe).

Sounds correct too, but in this case we might want to use the so-called stream library adapters that are for the next big version of Cycle.

**Comment by shesek** [comment]
> How bad would it be for readability if we wouldn't write `circular()` but the plugin would detect on its own?

Treating every reference to an undeclared variable as a circular dependency could turn ugly. I can easily see this happening by mistake due to a typo, coding error, etc. I would personally much prefer a more explicit, keyword-based approach.

**Comment by whitecolor** [comment]
I thought that it maybe an option in the plugin that you can use `keyword` and turn off implicit undeclared reference proxying.

**Comment by whitecolor** [comment]
> I can easily see this happening by mistake due to a typo, coding error, etc. 
Then you have to made typo two times) because to be proxied reference should not only be used in code, but also declared later in the scope.

**Comment by staltz** [comment]
I thought I had commented on this today, but my comment disappeared: the plug-in is experimental, so for now it is not the point to say whether it's good or bad. We should just experiment with it. That's why it is "experimental". :)

**Comment by whitecolor** [comment]
@staltz you have commented this in another issue)

**Comment by whitecolor** [comment]
I've updated plugin it now supports `rxjs v5`, `most` and imports `subject` if needed.

**Comment by staltz** [comment]
Great work @whitecolor.

**Comment by whitecolor** [comment]
@staltz I think using `ReplaySubject(1)` is more appropriate to use for creating proxy, Why would/could you prefer to use just `Subject` instead can you elaborate a bit?

**Comment by laszlokorte** [comment]
@whitecolor `shareReplay(1)` is mostly good for stream that contain state, like `state$ = model();`. You probably do not want to replay streams that contains events. Better explanation: https://github.com/cyclejs/core/issues/238#issuecomment-195310195

**Comment by whitecolor** [comment]
@laszlokorte thanks for the pointing to comment)

I'm trying to figure out the correct solution in term of circular dependency deal.

Say we have:
```js
let foo = Foo(events: bar.events$)
let bar = Bar(state$: foo.state$)
```
And lets say inside the `Bar` `events$` `startWith` something. We probably any why want this start value to get to bar if we want *really curcular dependency*. At least in most cases this would be the truth  (we can `skip(1)` if we don't need start value).

I probably believe that for curcular proxiying scenario `ReplaySubject(1)` maybe better default solution. Cycle core itself uses `ReplaySubject(1)` for creating `sinkProxies`.

I wonder if there is a case that make `ReplaySubject(1)` not desired for proxy subject scenario?

**Comment by staltz** [comment]
Because the subscribe (for replication real-to-proxy) happens at the end, there is no need for ReplaySubject because there is no "late subscriber". Replay is only useful for late subscribers. If the app logic requires saving the latest value for late subscribers, then we use shareReplay in the definition inside e.g. Bar.

PS: we most likely will not use anymore ReplaySubject in cycle core. Follow issue #196 for more on this.

**Comment by whitecolor** [comment]
> Replay is only useful for late subscribers. 

But without it subject will not get value that was on `startWith`, so it is kinda late. Or I miss something?

**Comment by staltz** [comment]
Maybe you're right.

**Comment by whitecolor** [comment]
Here simple circular case:

```js
var Double = (value$) => {
  var sink = value$.map(x => x*2).delay(1000).startWith(1)
  return sink
}

var proxy = new Rx.ReplaySubject(0)
var value$ = Double(proxy)
let proxySub = value$.subscribe(proxy)

value$.subscribe(x => {
  console.log('value', x)
})
```
Wont work with `Rx.ReplaySubject(0)` (just `Subject`) but will with `Rx.ReplaySubject(1)` because start value `1` will not get into the proxy as it is kinda late. If to put some even zero delay after startValue `.startWith(1).delay(0)` it will work, because will not be late.

Hm, and the problem that this won't work too:
```
var proxy = new Rx.ReplaySubject(0)
var value$ = Double(proxy.shareReplay(1))
let proxySub = value$.subscribe(proxy)
```
How to solve this without `ReplaySubject(1)`?

**Comment by laszlokorte** [comment]
if value$ is a state, Double itself should clarify that by calling `shareReplay(1)` itself. If value$ is just an event then replay is not needed and you wont care about missing the first value. (`startWith` indicates that it's a state stream so `shareReplay(1)` should be used in `Double`)

**Comment by whitecolor** [comment]
@staltz, @laszlokorte  what about such approach to circular:

```js
  let value$ = Observable.of(0).map(_ => bar.value$).flatMap(_ => _)
  const foo = Foo({value$, DOM})
  const bar = Bar({HTTP, prop$: foo.prop$})
```

This actually seem to work, and such:

```js
var Double = (value$) => {
  return value$.map(x => x*2).delay(1000) 
}

var value$ = Rx.Observable.of(0)
  .map(_ => double$).flatMap(_ => _)
  .startWith(1)
var double$ = Double(value$).share()

double$.subscribe(x => {
  console.log('value', x)
})
```

**Comment by tusharmath** [comment]
How about just simply using `Observable.defer` ? For instance —

```js
const proxy$ = Observable.defer(() => action$).shareReplay(1)
const action$ = mySelfDependantFunction(proxy$)

return proxy$
```

Is there a scenario that this approach wouldn't cover?

**Comment by staltz** [comment]
@tusharmath interesting! Thanks for that suggestion. Have you tried if it actually works? I'm excited there may be a way of not using proxy subjects.

**Comment by tusharmath** [comment]
@staltz Yes it does work. I have integrated it with some of my code and have also written tests — https://github.com/tusharmath/flo/pull/14/files#diff-ad387822cdad2615068fc6ffd58ba6faR2

**Comment by TylorS** [comment]
http://esnextb.in/?gist=82eb787c57ecc74315b02e982637d570

It sort of works, but it seems to throw an error for me, is there something I'm doing wrong?

**Comment by tusharmath** [comment]
@TylorS `onCompmleted` typo.

**Comment by TylorS** [comment]
@tusharmath That'll do it haha. Thanks :+1:

**Comment by whitecolor** [comment]
Yes it kinda works due to the fact that context execution of inner scope (function) goes actually synchronously after outer scope executed and inner scope has access to all variables defined in outer scope. But then the same technique could be used in cycle/core instead of subject stuff.

**Comment by whitecolor** [comment]
The problem that this creates infinite circular subscription and leaks http://www.webpackbin.com/NJoysrhxZ

Subscribtion is still have to me removed, but I' not sure even how it can be done in this case.

**Comment by tusharmath** [comment]
@whitecolor Yep, din't see that coming. Thanks for pointing out the memory leak.

**Comment by tusharmath** [comment]
@whitecolor I improved the implementation here — http://www.webpackbin.com/4kL0FJJ-W
Hopefully no memory leaks this time.

**Comment by whitecolor** [comment]
API of this thing is fairly complex. `reader` `writer`, it doesn't make code more readable and concise.

**Comment by tusharmath** [comment]
```js
// Sample function
const double = num$ => num$.map(x => x * 2).delay(100)

// Create proxy 
const p = proxy()

// Create Reader, reader is the input stream for my sample function
const source = p.reader()

// Writer takes the returned stream by my sample function and publishes it on the reader as well.
const out = p.writer(double(source.startWith(1)))

// The return value of the writer can be consumed everywhere.
out.take(10).subscribe(x => console.log(x))
```

@whitecolor I wouldn't say this is the best, but it suits my tastes. I would love to get more feedback about how I can improvise it. 

**proxy.js**

```js
export const proxy = () => {
  const subject = new Subject()
  return {
    reader: () => subject.asObservable(),
    writer: out => {
      let complete = false
      let refCount = 0
      const _out = out.replay(null, 1)
      const s0 = _out.subscribe(subject)
      let s1 = null
      return Observable.create(observer => {

        if (complete) {
          observer.onCompleted()
        }

        if (++refCount === 1) {
          s1 = _out.connect()
        }
        const s2 = subject.subscribe(observer)
        return () => {
          if (--refCount === 0) {
            s1.dispose()
            s0.dispose()
            complete = true
          }
          s2.dispose()
        }
      })
    }
  }
}

```

**Comment by whitecolor** [comment]
I've published this approach (lib agnostic using adapters):
https://github.com/whitecolor/cycle-circular

```js
import proxy from 'cycle-circular/xstream'  
  ...
  const value$ = proxy(_ => _.startWith(1))   
  const foo = Foo({value$, DOM})
  const bar = Bar({HTTP, prop$: foo.prop$})
  value$.proxy(bar.value$)
```

**Comment by tusharmath** [comment]
@whitecolor Looks good, how about yet another approach —

```js

import {Subject, Observable} from 'rx'


const double = (src$) => src$.map(x => x * 2).delay(100)

const subject = new Subject()
const value$ = double(subject.asObservable().startWith(1).tap(x => console.log(x)))
const out$ = value$.multicast(subject).refCount()


out$.take(10).subscribe(x => bin.log(x))
```

**Comment by whitecolor** [comment]
@tusharmath made it agnostic to stream library, without rx specifics

**Comment by staltz** [comment]
This seems done now thanks to @whitecolor and others. :)

**Comment by whitecolor** [comment]
After some investigation It seems that for rx/most non-leaking proxy is not possible :disappointed: without inner cycle detection custom logic is needed like it is done in `xstream`.

**Comment by dalgard** [comment]
The problem with circular dependencies seems to add a lot of complexity and cognitive overhead to Cycle. I, for one, barely understand the problem.

Is the problem solved with the advent of xstream, or is it necessary to use a library?

Does every Cycle app encounter this problem?

**Comment by Widdershin** [comment]
> The problem with circular dependencies seems to add a lot of complexity and cognitive overhead to Cycle. I, for one, barely understand the problem.

Yep, I have the same feeling, took me a very long time to get a basic grip on circular dependencies.

> Is the problem solved with the advent of xstream

Yes, you can use `.imitate()` in xstream. The problem is solved in the sense that it works, but it is still hard to read and reason about.

> Does every Cycle app encounter this problem?

No Cycle app I have ever seen requires an inner circular dependency. It can always be rewritten in terms of a fold. If someone has a code example they feel disproves this please share.

So it occasionally comes up but you never *need* a circular dependency. It's useful sometimes, but I find it's best to move it from app code to library code. For example, allowing components to remove themselves in `@cycle/collection` is done with a circular dependency.
