### ISSUE TITLE
Write Cycle Nested documentation on cycle.js.org 

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#187]
- [x] Replace *Custom Elements* chapter with *Components*.
- [x] MVI Chapter to conclude mentioning the next *Components* chapter.
- [ ] Proxy / circular ref Chapter
- [ ] Drivers chapter should explain how drivers should implement `isolateSource()` and `isolateSink()`
- [x] Update all examples to use hyperscript-helpers, response=>source
- [x] Use more `diff`
- [x] New frontpage

**Comment by gyzerok** [comment]
@staltz it seems like creating dynamic list of Components and reacting to ones events need to be added to the docs.

**Comment by fobos** [comment]
@staltz I'm really looking forward to read doc about Components as soon as possible because now I'm disappointed that Custom Elements deprecated and want to understand new concept.

**Comment by Frikki** [comment]
@fobos Read this blog post for an understanding of nested components http://staltz.com/unidirectional-user-interface-architectures.html

**Comment by staltz** [comment]
Stale. 

https://github.com/cyclejs/core/issues/341
