### ISSUE TITLE
run() should be synchronous

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#200]
Discussion that started here https://gitter.im/cyclejs/cycle-core?at=569934f75de13b3f15e34af6

The problem is:
- We may want to use sources or sinks that Cycle.run returns to inspect something
- AND the main() and the drivers may run synchronously (like they do in some tests or e.g. server side rendering)

Current solution to that is to delay (with setTimeout) actual execution internally in run(). The discussion shows hows that's not nice in some cases.

One possible solution is to scrap the `const {sinks, sources} = run(main, drivers);` API and use instead just `const subscription = run(main, drivers);`, if people need to inspect the sinks and sources, they can wrap `main` in a function `mainWithInspections` which intercepts sources and sinks.

Feedback? @Frikki @TylorS 

And @Widdershin this could be relevant to `restart` since I know you were using `{sinks, sources}` from run().

- - -

## Decided the API

**"I want the sources and sinks from execution"**:
```js
const {sources, sinks, run} = Cycle(main, drivers);
// ... use sources and sinks here ...
run(); // starts it synchronously
```

**"I don't care about sources and sinks from execution"** (backwards compatible):
```js
Cycle.run(main, drivers); // starts it synchronously
```

And `run()` would always return a Disposable / Subscription.

Would incur breaking change because all Core tests would need to be updated. Cycle DOM tests should be updated accordingly too.

**Comment by laszlokorte** [comment]
> One possible solution is to scrap the const {sinks, sources} = run(main, drivers); API and use instead just const subscription = run(main, drivers);, if people need to inspect the sinks and sources, they can wrap main in a function mainWithInspections which intercepts sources and sinks.

Currently I am doing:

```es6
// Cycle 1
const drivers = {
  DOM: makeDOMDriver('#app-main'),
  preventDefault: preventDefaultDriver,
  keydown: keyboardDriver,
};
// Cycle one emits a stream of "pla data"
const {sinks: {plaData$}} = Cycle.run(kv, drivers);

// Cycle 2
const driversAssistent = {
  DOM: makeHammerDriver(makeDOMDriver('#app-assistent')),
  preventDefault: preventDefaultDriver,
  keydown: keyboardDriver,
  props$: () => O.just({}),
  // Cycle 2 cosumes the stream of pla data
  data$: () => plaData$,
};
Cycle.run(pla, driversAssistent);
```

How would I do that with the `mainWithInspections ` api?

**Comment by laszlokorte** [comment]
Another idea:
```
const myCycle = Cycle(main, drivers);
const {sinks, sources} = myCycle;
// could be done whenever I want, inside setTimeout or inside setAnimationFrame:
myCycle.run();
```
Or If I just do not care
```es6
Cycle(main, drivers).run();
```

**Comment by staltz** [comment]
Your usage isn't recommended. You should have just one run. Usually we should just have one DOM driver, but I think it's better to have two DOM drivers than to have two run instances.

**Comment by whitecolor** [comment]
#200 should be success)

If results of `run` can used only acyncroniously they probably shoud be deferred before can be accessed, using subscription in case of cycle. I don't really understand the problem though, what is wrong with `{sinks, sources}` returned as synchronious result of `run` without setTimeout currently used?

**Comment by laszlokorte** [comment]
@whitecolor the Problem is that if setTimeout is not used, there will be items already emitted by the `source` and `sink` observables before a subscriber has a chance to listen (subscribers can only be added after `run` already returned). Those items will be lost.

@staltz I see that my usage s not recommended for developing a applications. What I am currently working at is a set of small widgets that can be embedded in otherwise static pages (like blogposts, tutorials, articles). Imagine something like jsbin or jsfiddle embeddings but without the possibility to edit the code or something like those widgets on this page: http://worrydream.com/LadderOfAbstraction/
I am developing each widget as it's own cycle application / data flow component but the whole page in which they will be included in the end will not be a cycle application. I need some of the components, when embedded on the same page being able to communicate.
The current possibility to take the sinks of one cycle and pass it into another cycle as sources  is almost perfect for that use case. And I think it makes perfect sense for a cycle to provide it's sources and sinks to the outside as kind of "waste heat".

I understand that not being the recommended usage my use case might not drive your decisions in terms of api design but I did not want to miss the chance at least giving some support for the current api :smile:

**Comment by Widdershin** [comment]
I do indeed rely upon sources and sinks in cycle-restart, but it could always be adapted to work with a synchronous run. As long as there is still some way to get a reference to sources and sinks, I'm happy.

**Comment by staltz** [comment]
@laszlokorte Yeah in general I'd still like to support exporting sinks and sources for others to fiddle as they wish.

@Widdershin I saw the src for restart, and basically you're using `sources.Foo.log()` but not `sinks`.

Another option, which is not pretty, is `prerun`:

```js
const {sources, sinks} = Cycle.prerun(main, drivers);

// ... Use sources and sinks ...

Cycle.run(sources, sinks);
```

**Comment by staltz** [comment]
And yet another option is a callback given to `run`:

```js
Cycle.run(main, drivers, (sources, sinks) => {
  // ... Use sources and sinks ...
});
```

Other ideas please?

**Comment by staltz** [comment]
I just noticed the `prerun` idea is essentially the same as @laszlokorte suggested.

**Comment by Widdershin** [comment]
@staltz restart does use sinks, but only for the sake of disposal. If `sources.dispose` also disposes of `sinks` then everything would be fine. (I feel like I might not really understand what `sources.dispose` does vs `sinks.dispose`)

**Comment by staltz** [comment]
`source.dispose` might or might not be available, it is implemented in drivers (DOM Driver has dispose, others may not have). `sink.dispose` is getting rid of the proxySink subject.

On the other hand, we can just return a Disposable from `run()`, which can be used to dispose everything.

**Comment by staltz** [comment]
Right now I'm starting to prefer @laszlokorte's solution, adapted to be backwards compatible:

**"I want the sources and sinks from execution"**:
```js
const {sources, sinks, run} = Cycle(main, drivers);
// ... use sources and sinks here ...
run(); // starts it synchronously
```

**"I don't care about sources and sinks from execution"** (backwards compatible):
```js
Cycle.run(main, drivers); // starts it synchronously
```

Opinions on this? @TylorS @erykpiast @Frikki @laszlokorte @Widdershin

**Comment by TylorS** [comment]
That seems like a sound way to go to me. Just so I'm clear; testing would be as follows

```js

const {sources, sinks, run} = Cycle(main, drivers)

sources.DOM.observable.skip(1).take(1).subscribe(root => {
  // assert stuff
})

run() // makes all the stuff above work (?)
```

Also, does it feel cluttered when we need `dispose()` as well with the (proposed) adapter API?
```js
const {sinks, sources, dispose, run} = Cycle(main, drivers, options)
```

**Comment by staltz** [comment]
First snippet was correct. Second was wrong. `run()` returns a disposable.

```js
const {sources, sinks, run} = Cycle(main, drivers)

sources.DOM.observable.skip(1).take(1).subscribe(root => {
  // assert stuff
})

const disposable = run() // makes all the stuff above work

disposable.dispose();
```

**Comment by TylorS** [comment]
Sounds like a solid plan to me. Seems to cover all the bases. 

- synchronous
- access to sinks
- access to sources
- disposable

**Comment by staltz** [comment]
Yeah I can try to come up with teachable concepts out of that.

```js
const {sources, sinks, run} = Cycle(main, drivers);
// Plugs together main and drivers in a cycle
```

```js
run();
// Execute the cycle
```

**Comment by whitecolor** [comment]
Won't this
`
const {sources, sinks, run} = Cycle(main, drivers);
run()
`
be sthe same
```
const {sources, sinks} = Cycle.run(main, drivers); // where `run` executes synchoriously last
```
?

**Comment by staltz** [comment]
No, not really. We are talking about this problem
```js
const {sources, sinks} = Cycle.run(main, drivers);
sources.DOM.observable.skip(1).subscribe(el => {
  // Never gets anything because by the time we called run, it synchronously
  // executed and COMPLETED as an Rx Subject, so when subscribed later,
  // nothing happens.
});
```

**Comment by whitecolor** [comment]
@staltz Ok I got and removed the question. So then I think
```javascript
const {sources, sinks, run} = Cycle(main, drivers);
```
while preserving existing API looks good, up to you.

**Comment by staltz** [comment]
Cool, that's probably what we are going to do

**Comment by laszlokorte** [comment]
Yeah looks good to me.

**Comment by erykpiast** [comment]
I guess I don't know the background, but I wonder what is with about `ReplaySubject`? If missed values are the only problem it'll do the job.

**Comment by laszlokorte** [comment]
When using ReplaySubject you have to choose a buffer size. You can not know how many items may be missed so you would have to use a very large buffer which is not practical in terms of performance / memory consumption.

**Comment by erykpiast** [comment]
Ok, get it. I was thinking about buffer size 1, but obviously not only the last value matters here.

**Comment by staltz** [comment]
This is now done with Cycle Diversity.
