### ISSUE TITLE
Docs and examples on animation

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#218]
_From @Willmo36 on July 2, 2015 7:57_

This might be more of a virtual-dom issue, but I think it's worth documenting animation for custom widgets. Mithril has a great write-up (http://lhorie.github.io/mithril-blog/velocity-animations-in-mithril.html) on how to use velocity.js with it's vdom. The exit animations section is particularly interesting.

_Copied from original issue: cyclejs/cycle-dom#18_

**Comment by staltz** [comment]
Made this https://github.com/cyclejs/examples/tree/master/animation

**Comment by littleStudent** [comment]
If anyone is coming across this (n1 search result for cyclejs + animations).
here is the new link: https://github.com/cyclejs/cyclejs/tree/master/examples/animation

**Comment by p-adams** [comment]
@littleStudent  I get a 404 for the above page.

**Comment by BrianSemiglia** [comment]
I was able to achieve animations by using a `sample` filter and collection type for my store. However, this was for a version of Cycle I attempted in Swift. https://github.com/BrianSemiglia/Cycle.swift#animations
