### ISSUE TITLE
DOM.select() does not properly select an element when it is the root of an isolated vTree.

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#227]
_From @TylorS on February 2, 2016 22:49_

When a *plain* element e.g. `<button />` is used as the root of an isolated vTree DOM.select('button')
is unable to properly select the element and listen for it's events.

An example from @juliomarcos (thank you!)
https://jsbin.com/dadilavoca/edit?js,output

Adding a classname to the button element and using DOM.select('.classname') instead works as expected. 

This does **not** seem to affect DOM.select('button').observable

@laszlokorte mentioned having issues with DOM.select('*') as well which may or may not be related.

_Copied from original issue: cyclejs/cycle-dom#96_

**Comment by staltz** [comment]
Thanks for the report

**Comment by staltz** [comment]
_From @TylorS on February 3, 2016 17:38_

@staltz  This happens because when the namespaces are merged together from the namespace `['.cycle-scope-1', 'button']` becomes `.cycle-scope-1button` and not `button.cycle-scope-1`

**Comment by staltz** [comment]
_From @laszlokorte on February 3, 2016 17:42_

I think the issue with `DOM.select('*')` that I came across has the same reason that the selector becomes `.cycle-scope1*` which is not even a valid selector but throws when used with `matches()` or `querySelector()`

**Comment by staltz** [comment]
_From @TylorS on February 3, 2016 18:4_

Sorting the namespace is one possible solution for both cases of '*' and 'button'
```js
const isValidString = param => typeof param === `string` && param.length > 0
const startsWith = (string, start) => string[0] === start
const isSelector = param =>
    isValidString(param) && startsWith(param, `.`) || startsWith(param, `#`) ||
    startsWith(param, ':')
  

function sortNamespace(a, b) {
  if (isSelector(a) && isSelector(b)) {
    return 0
  }
  return isSelector(a) ? 1 : -1
}
```

Then [here](https://github.com/cyclejs/cycle-dom/blob/master/src/render-dom.js#L206)
becomes:
```js
namespace.concat(trimmedSelector).sort(sortNamespace)
```

**Comment by staltz** [comment]
_From @laszlokorte on February 3, 2016 19:29_

Maybe `startsWith(param, ':')` as well to support `:first-child` etc

**Comment by staltz** [comment]
_From @TylorS on February 3, 2016 19:40_

Good call :+1: 
Updated the above example

Do you think that '*' should be a 'selector' ?

**Comment by staltz** [comment]
_From @laszlokorte on February 3, 2016 19:45_

I think 'selector' is not the best name here because in css terms `button` is a selector too.

There might be some css specification in which order parts of a selector need to be when concatenated.

**Comment by staltz** [comment]
_From @TylorS on February 3, 2016 19:46_

Good point. I'll try to find something

**Comment by staltz** [comment]
_From @laszlokorte on February 3, 2016 20:10_

> A sequence of simple selectors is a chain of simple selectors that are not separated by a combinator. It always begins with a **type selector** or a **universal selector**. No other type selector or universal selector is allowed in the sequence.

https://www.w3.org/TR/selectors/#selector-syntax

**type selector**: an element (`button`, `div`, `a`...)
**universal selector**: `*`
(I am not sure if we need support for namespaced selectors, never saw them used in any real code)

So the check could be inverted to test only for `*` and `^[a-z]`

**Comment by staltz** [comment]
_From @TylorS on February 3, 2016 20:16_

It probably should be inverted there are way more checks for 'selectors' here

**Comment by staltz** [comment]
Looks like you two are quite close to agreeing on a PR

**Comment by staltz** [comment]
_From @tanjucat on February 5, 2016 15:19_

TylorS says:
> Adding a classname to the button element and using DOM.select('.classname') instead works as expected.

But, as can be seen in the referenced [example](https://github.com/cyclejs/cycle-examples/issues/17), I've seen the problem for `button` even when it is selected using a class name (I tried element id as well).

**Comment by TylorS** [comment]
This is a solved issue in Cycle DOM v10

**Comment by staltz** [comment]
Yeah, let's close it so it doesn't get our attention again
