### ISSUE TITLE
DOM events should be processed from inner to outer component

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#229]
_From @laszlokorte on February 10, 2016 0:43_

Currently the order in which listeners are notified depends on the order they are attached.

If we have one parent component P and one child component C and both components create streams of click events `DOM.select(':root').events('click')` it might occur that the parent component P get's notified of a click before the child C get's notified.
The order is determined by which stream get's subscribed first.

The correct bubbling behavior would be to notify the child component first. So the child component can have a chance to stop the event's propagation and prevent the parent from getting the event.

If `useCapture` is set to true the order should be inverted: If both components set useCapture to true the parent should always be notified first.

_Copied from original issue: cyclejs/cycle-dom#101_

**Comment by staltz** [comment]
Fully agreed

**Comment by laszlokorte** [comment]
Why have those issues moved from cycle-dom to cycle-core?

**Comment by staltz** [comment]
Me and @TylorS decided to have just one repo for all Cycle.js issues. It makes issue management much more sane, with one place to look for issues, consistent labeling, etc.

**Comment by staltz** [comment]
This is now done in Cycle DOM v10.0.0-rc13
