### ISSUE TITLE
Fix module export 

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#230]
_From @staltz on February 15, 2016 8:46_

See https://github.com/rollup/rollup/issues/366

_Copied from original issue: cyclejs/cycle-dom#102_

**Comment by kamilogorek** [comment]
Would you rather move to ES6 exports or tinker about how to make it work using commonjs?

**Comment by staltz** [comment]
Move to ES6 exports

**Comment by kamilogorek** [comment]
One way to preserve both, default and named exports is to use simple clause

```js
export {
  CycleDOM as default,
  makeDOMDriver,
  makeHTMLDriver,
  h,
  hJSX,
  svg,
  mockDOMSource
}
```

However problem there is that `hyperscript-helpers` are using spread operator to attach theselves to `CycleDOM` object. As of now (and probably never?) it's not possible to spread object values to export clause, eg.

```js
export {
  makeDOMDriver,
  h,
  ...hh
}
```

We also have to detach `hJSX` from `CycleDOM` object to make it possible being exported without using `export { CycleDOM.hJSX }` directly.

**Comment by staltz** [comment]
This issue looks stale, and we could easily solve this later on by changing the compile target of TypeScript.
