### ISSUE TITLE
response$.request should be read-only

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#232]
_From @staltz on July 6, 2015 16:8_

Use `Object.defineProperty` to make a no-op setter for `request` property under `response$`.

_Copied from original issue: cyclejs/cycle-http-driver#7_

**Comment by chadrien** [comment]
Should `request`'s properties be also read-only?

I volunteer to PR this :)

**Comment by staltz** [comment]
Hi @chadrien thanks for volunteering. I believe the properties don't need to be read-only, and this feature suggestion should work so that if someone tries to set `response$.request`, it will raise a warning in the console for instance.

**Comment by chadrien** [comment]
Alright, will do so :+1:

**Comment by staltz** [comment]
I removed `help wanted` so you are now "assigned" to this :)

**Comment by chadrien** [comment]
`Object.defineProperty` / `Object.freeze` both throw a `TypeError` when trying to write a read-only attribute. So if we only want a warning in console we would need a `Proxy` that could `try/catch` internally. Is that OK with you or is it too much "complexity" and throwing a `TypeError` would be OK?

**Comment by staltz** [comment]
Throwing TypeError would be ok :)

**Comment by staltz** [comment]
This is done long ago. :D
