### ISSUE TITLE
How to handle click on child elements?

### ISSUE THREAD

**Issue by ronag** [cyclejs/core#244]
I'm trying to build a simple list with several items inside. Each item has a specific id and the `Item` component will internally fetch the required data. The only thing the list has to pass down is the id and whether or not is is selected.

I've been trying to figure this, relatively simple scenario out for a while without progress.

In particular I have issues with `toggleSelected$`... Another problem with the current implementation is that as soon as the `selected` state is changed all the items are reloaded which causes flimmering when loading their thumbnails...

```javascript

function intent({ DOM, HTTP }) {
  const ids$ = HTTP.select(...)
  const toggleSelected$ = ???
  return {
    ids $
    toggleSelected$
  }
}

function model(actions) {
   const selected$ = toggleSelected$
     .scan((selected, id) => {
       const idx = selected.indexOf(id)
       if (idx !== -1) {
         selected = selected.slice(0).splice(idx, 1)
       } else {
         selected = [...selected, id]
       }
       return selected
     }, [])
  const ids$ = actions.ids$
  return Observable.combineLatest(selected$, ids$, (selected, ids) => ({ selected, ids }))
}

function view({ state$, items$ }) {
  return items$
    .startWith([])
    .map((items) =>
      div({ style: styles.list }, [ items ])
    )
}

function List(sources) {
  const actions = intent(sources)
  const state$ = model(actions)

  const items$ = state$
    .map(({ ids, selected }) => ids
      .map(id => Item({
        ...sources,
        props$: Observable.of({ id, selected: selected.indexOf(id) !== -1 }),
      }))
    )

  return {
    DOM: view({
      state$,
      items$: items$
        .flatMapLatest(items => Observable
          .combineLatest(
            Observable.of(null),
            ... items(asset => item.DOM),
            (... items) => items(x => x)),
        ),
   }
}

export default isolate(List)
```

**Comment by ronag** [comment]
@TylorS: The problem with closing "discussions" is that no one will look into them once they've been closed... i.e. I have a problem here and there is no easy way to see whether a solution has been found or not...

**Comment by staltz** [comment]
<img width="925" alt="screen shot 2016-02-26 at 17 24 41" src="https://cloud.githubusercontent.com/assets/90512/13356421/d7a01cea-dcad-11e5-8253-dc3a958f2bf1.png">

Look at that link there to "Read discussion issues"
