### ISSUE TITLE
Issues with JSDOM

### ISSUE THREAD

**Issue by mciparelli** [cyclejs/core#245]
I'm trying to run a simple application with JSDOM, as it makes my life simpler to test DOM stuff in node.
I'm running this code:
```js
const window = jsdom('<div class="cycle-test"></div>').defaultView;
global.document = window.document;
const main = () => ({ DOM: Observable.just(div('test')) });
run(main, {
  DOM: makeDOMDriver('.cycle-test')
});
```
And I get `[TypeError: Cannot read property 'properties' of undefined]`. I dug and figured out that `oldVTree === undefined` here: https://github.com/cyclejs/dom/blob/master/src/render-dom.js#L42

Same code runs fine in browser.

**Comment by mciparelli** [comment]
oh wait a min, I think it's very much related to https://github.com/cyclejs/core/issues/222

**Comment by staltz** [comment]
@mciparelli, just out of curiosity, can you try this with Cycle DOM v10 which uses an entirely different implementation? I just want to know if this is still a relevant issue.

**Comment by mciparelli** [comment]
Yeah this is no longer an issue. Code runs fine. JSDOM users simply have to make sure to have `document` defined in the global namespace or you get a
```
ReferenceError: document is not defined
    at Object.getElement (/path/to/node_modules/@cycle/dom/lib/utils.js:12:9)
```
which I guess makes total sense since this is a DOM lib.
