### ISSUE TITLE
Drivers using other drivers?

### ISSUE THREAD

**Issue by ronag** [cyclejs/core#246]
Lets say I'm using the http driver to fetch data from my server. I've noticed that a lot of different places in my application uses the same data so I would like to centralise/cache the requests/response in a driver.

However, the driver would need to use http/websocket driver internally to implement the caching.

How would I go about this? Basically what I need is some kind of higher order driver...

**Comment by TylorS** [comment]
Though I'm closing this issue, discussion is free to continue. This is going to be our new policy for github issues.

This is actually quite easy. You can see [this router driver](https://github.com/TylorS/cyclic-router) I wrote which expects a history driver as a parameter. Another option is to create the other driver inside of yours and use it from there.

e.g.
```js
function makeYourDriver(httpDriver) {
  return function yourDriver(sink$) {
    const source$$ = httpDriver(sink$) 
    //add extra functionality
  }
}

const httpDriver = makeHttpDriver(...)

Cycle.run(main, {
  yourDriver: makeYourDriver(httpDriver)
})

//or

function makeYourDriver(options) {
  return function yourDriver(sink$) {
    const httpDriver = makeHttpDriver(options)
    const source$$ = httpDriver(sink$) 
    // add functionality to the httpDriver here
  }
}

Cycle.run(main, {
  yourDriver: makeYourDriver(options)
})
```

There really is no wrong way, just what you believe to be best for you use case.

**Comment by ronag** [comment]
Makes sense. Thanks!
