### ISSUE TITLE
flatMerge & flatCombine

### ISSUE THREAD

**Issue by ronag** [cyclejs/core#250]
This is more of a helper/optimization suggestion that maybe should go in some form of "best practice/helper" section?

Often we come in a situation where we need to merge the sinks of a stream of sinks. This especially common when working with nested children whom need to be either combined (DOM) or merged (usually everything but DOM).

Usually you would do this:

```javascript
const items$ = state$
  .pluck('items')
  .map(items => items.map(item => Item({ ...sources, props$: Observable.of(item))
  .shareReplay(1)

return {
   DOM: items$.flatMapLatest(items => Observable.combineLatest(...items.map(item => item.DOM), (...items) => view({ items }))
   HTTP: items$.flatMapLatest(items => Observable.merge(...items.map(item => item.HTTP))
}
```

which is rather inefficient since `flatMapLatest` will not reuse existing subscriptions. Instead I would suggest something like:

```javascript
const items$ = state$
  .pluck('items')
  .flatCombine(item => Observable.of(Item({ ...sources, props$: Observable.of(item))), (...items) => items)
  .shareReplay(1)

return {
   DOM: items$.flatCombine(item => item.DOM, (...items) => view({ items })),
   HTTP: items$.flatMerge(item => item.HTTP)
}
```

```javascript
export function flatMerge(selector) {
  const pairs$ = this
    .startWith([])
    .pairwise()
    .share()

  const add$ = pairs$
    .flatMap(([prev, curr]) => curr.filter(x => prev.indexOf(x) === -1))
  const remove$ = pairs$
    .flatMap(([prev, curr]) => prev.filter(x => curr.indexOf(x) === -1))

  return add$
    .flatMap(x => selector(x).takeUntil(remove$.filter(remove => remove === x)))
}

export function flatCombine(selector, combiner) {
  // TODO: Optimize
  return this
    .flatMapLatest(items => Observable
      .combineLatest(
        Observable.of(null),
        ...items.map(selector),
        (...items) => combiner(...items.filter(x => x))),
    )
}

```

Thoughts?

The next thing to get the performance with nested components story finished is to solve the re-evaluation inside `const items$ = ...`.

We need something similar for optimizing `flatMapLatest` + `combineLatest` the same way this optimises `flatMapLatest` + `merge`.

**Comment by ronag** [comment]
Related https://github.com/cyclejs/core/issues/204

**Comment by TylorS** [comment]
> flatMapLatest will not reuse existing subscriptions.

Why not use just `flatMap()` ?

**Comment by ronag** [comment]
@TylorS: Because `flatMap` while not cancel running subscriptions... has to be `flatMapLatest`.
