### ISSUE TITLE
Stream transposition in dom driver

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#251]
1) The general question is what is the use cases for passing stream to `vtree`?

2) The particular question of use case:
When sending stream to `vtree` like that (`inputDOM$`):

```js
function MyInput ({DOM}){
  let value$ = DOM.select('input').events('input')
    .map(ev => ev.target.value)
    .startWith('type here')
  return {
    DOM: value$.map(value => input({value}))
  }
}

function main ({DOM}) {
  const add$ = DOM
    .select('.add')
    .events('click')
    .map(ev => 1);

  const count$ = add$
    .startWith(0)
    .scan((total, change) => total + change)

  let myInput = MyInput({DOM})

  let inputDOM$ = myInput.DOM

  return {
    DOM: count$.map(count =>
    div('.counter', [
      'Count: ' + count,
      button('.add', 'Add'),
      inputDOM$
    ])
  ) 
  };
}
```

each time `count$` has new value input starts with `type here` initial value.

is it possible to get somehow the behaviour like with using `combineLatest`:
```js
DOM: Rx.Observable.combineLatest(count$, inputDOM$, (count, inputDOM) =>
    div('.counter', [
      'Count: ' + count,
      button('.add', 'Add'),
      inputDOM
    ])
  )
```
?

**Comment by staltz** [comment]
> is it possible to get somehow the behaviour like with using combineLatest

Yes it is, you just need to make `inputDOM$` hot:

```js
let inputDOM$ = myInput.DOM.publish()
inputDOM$.connect()
```

**Comment by whitecolor** [comment]
@staltz thanks, but is a good practice? What would you suggect to use in this cases `publish/connect` or `combineLatest`?

Aslso in what cases would you suggest to pass streams to vtree?

Can you ellaborate?
