### ISSUE TITLE
Solve memory leak with circular dependencies of streams

### ISSUE THREAD

**Issue by ronag** [cyclejs/core#257]
This is an issue I keep getting stuck at in different context. When the parent needs to listen of events of the child, how do you break or avoid a cycle?

e.g.

```javascript

function List(sources) {
  const actions = intent({ ...sources, click$: ??? })
  const state = model(actions).shareReplay(1)

  const items$ = state
    .flatMapLatest(({ items, selected }) => 
      items.map(item => Item({ 
        ...sources, 
        props$: Observable.of({ id: item.id, selected: item.id === 'selected' })
      }))

  const click$ = items$.map(items => Observable.merge(...items.map(item => item.click$)))

  return {
    ...
  }
}
```

Basically the following flow:

click => List => selected => Item => click

Which gives me a cycle. How do I get around this? I could use a proxy as I've seen in some examples:

```javascript
  const clickProxy = new Subject()
  const actions = intent({ ...sources, click$: clickProxy })

  const subscription = click$.subscribe(clickProxy)

  // subscription leaks...
```

However, that gives me a memory leak...

**Comment by staltz** [comment]
The cycle is unavoidable, the proxy technique is needed. Good question how to avoid the memory leak.

**Comment by staltz** [comment]
Let me actually open this as a bug and rename the title.

**Comment by TylorS** [comment]
It is totally situation dependent, but using `click$.takeUntil(something$).subscribe(clickProxy)` might work in some situtations.

**Comment by ronag** [comment]
Other alternatives I've been thinking of is using form of driver or `Observable.using`, but nothing really feels good...

**Comment by TylorS** [comment]
@ronag Is there something triggered by a `source` that causes this component to be removed from view? e.g. a route change from sources.history or source.router or anything like that?

**Comment by ronag** [comment]
@TylorS: It could be various things. e.g. hot reloading, update from a driver, web socket data...

**Comment by ronag** [comment]
One more alternative I guess would be to do it similar to flux and a "dispatch" driver where one can send namespaces events in a global fashion. That way the List could subscribe to those, similar to `DOM.select`.

**Comment by TylorS** [comment]
I tried to think more on this.

**Comment by staltz** [comment]
I'm thinking about this as well, and it's basically the subscription chain inside operators. If you have a chain `a$ -> b$ -> c$`, it's unsubscribed from `c$` to `b$` to `a$`. With a free-standing subscription, it's not in the operator subscription chain, so it doesn't get automatically unsubscribed. The trick is to somehow include the proxy subscription in that chain.

**Comment by ronag** [comment]
A ugly solution would be:

```javascript
return {
   DOM: Observable.using(() => click$.subscribe(clickProxy), () => view({ state$ }))
}
```

**Comment by staltz** [comment]
`using` may work. Either that way, or this other way: the resource could be the proxy Subject, because it should be a disposable as well. Have you tried this?

```
 Observable.using(
  () => new Subject(),
  (proxyItemAction$) => {
    const actions = intent(DOM, hashchange, initialHash, proxyItemAction$);
    const state$ = model(actions, sourceTodosData$);
    const amendedState$ = state$.map(amendStateWithChildren(DOM)).shareReplay(1);
    const itemAction$ = amendedState$.flatMapLatest(({list}) =>
      Observable.merge(list.map(i => i.todoItem.action$))
    );
    itemAction$.subscribe(proxyItemAction$);
    return view(amendedState$)
  }   
)
```

**Comment by staltz** [comment]
We may be able to create a wrapper/abstraction/helper for this all, maybe related to #170.

**Comment by ronag** [comment]
@staltz: A helper would be nice. I'm having a little trouble wrapping my head around this.

**Comment by staltz** [comment]
Because it's possible to solve with just Rx (and `Observable.using`), I'll mark this as feature suggestion, not bug.

**Comment by ronag** [comment]
@staltz: This doesn't feel quite solved. 

Take the following more advanced example:

```javascript
function Grid(sources) {
  const click$ = new Subject()

  const actions = intent({ ...sources, click$ })
  const state$ = model(actions).shareReplay(1)

  const items$ = state$
    .pluck('items')
    .flatMapLatest(items => items.map(id => Asset({
      ...sources,
      props$: state$
        .pluck('selected')
        .map(selected => selected.includes(id))
        .distinctUntilChanged()
        .map(selected => ({ id, selected })),
    })))
    .shareReplay(1)

  // Leaks
  items$
    .map(items => items.map(item => item.click$))
    .flatMapLatest(items => Observable.merge(...items))
    .subscribe(click$)

  return {
    DOM: view({
      state$,
      items$: items$
        .map(items => items.map(item => item.DOM))
        .flatMapLatest(items => items.length
          ? Observable.combineLatest(...items, (...items) => items)
          : Observable.of([])
        ),
    }),
    HTTP: 
      items$
        .map(items => items.map(item => item.HTTP))
        .flatMapLatest(items => Observable.merge(...items))
  })
}
```

What stream do you hook up with `Observable.using`. With my suggestion it's kind of undefined and I am confused on how to apply your suggestion on this, since your example only returns a single sink.

**Comment by ronag** [comment]
Updated comment above with helper suggestion.

**Comment by sdebaun** [comment]
I have heard of use cases that might need subjects, but so far we've managed to avoid explicit use of them in sparks-cyclejs.

@ronag check out how we're handling this --
https://github.com/sdebaun/sparks-cyclejs/blob/release/src/components/sdm/List.js

So far this pattern has worked great for us, its 'turtles all the way down'.

**Comment by whitecolor** [comment]
I believe leak with proxy subject can be avoided using `finaly`:

```js
var proxySubject = new Rx.Subject()

let source2 = proxySubject.map(x => x*2)

var source = Rx.Observable.timer(0, 1000)
.do(x => console.log('timer', x))
.finally(() =>  proxySubscription.dispose())
let proxySubscription = source.subscribe(proxySubject)

let sub = source.subscribe(x => {
	console.log('source', x)
})
let sub2 = source2.subscribe(x => {
	console.log(' source2', x)
})
setTimeout(() => {
  console.log('DISPOSE')
  sub.dispose()
  sub2.dispose()
}, 2500)
```

`babel` plugin (https://github.com/cyclejs/core/issues/170) definitly will be needed for this)

**Comment by whitecolor** [comment]
I believe leak with proxy subject can be avoided using `finally` that catches termination of the stream:

```js
var proxySubject = new Rx.Subject()

let source2 = proxySubject.map(x => x*2)

var source = Rx.Observable.timer(0, 1000)
.do(x => console.log('timer', x))

// most I dont like this reassign, though its all hacky way
souce = souce.finally(() =>  proxySubscription.dispose())
let proxySubscription = source.subscribe(proxySubject)

let sub = source.subscribe(x => {
	console.log('source', x)
})
let sub2 = source2.subscribe(x => {
	console.log(' source2', x)
})
setTimeout(() => {
  console.log('DISPOSE')
  sub.dispose()
  sub2.dispose()
}, 2500)
```
https://jsfiddle.net/prinzC/sk4eygaj/

`babel` plugin (https://github.com/cyclejs/core/issues/170) definitly will be needed for this)

**Comment by brucou** [comment]
Just curious, would it work to create a `circularSubscribe` method, so you can replace `let proxySubscription = source.subscribe(proxySubject)` by `let proxySubscription = source.circularSubscribe(proxySubject)`, and with : 

```
Rx.Observable.prototype.circularSubscribe = function (proxySubject) {
  var source = this;
  var disposable =  source.subscribe(proxySubject);
  var onCompletedHandler = function () {
    disposable.dispose();
  }
  proxySubject.subscribe(noop, noop, onCompletedHandler);
  return disposable;
}
```

**Comment by brucou** [comment]
What do you mean by 'terminated with dispose'? Streams complete, but are not disposed. Subscriptions are disposed and vanilla subjects too. Do you refer to the fact that when a subscription is disposed, it triggers a chain of subscriptions disposals? That's how `finally` works under the hood for sure. The interesting part of the source code is here : 

```
FinallyDisposable.prototype.dispose = function () {
  if (!this.isDisposed) { // IF NOT DISPOSED ALREADY
    var res = tryCatch(this._s.dispose).call(this._s); // DISPOSE THE SUBSCRIPTION TO THE UPPER OBSERVABLE
    this._fn(); // CALL THE SELECTOR FUNCTION ERROR (WHILE DISPOSING) OR NOT
    res === errorObj && thrower(res.e); // IF ERROR PROPAGATES THE ERROR
  }
};
```

That said, going back to your proposed code (the `jsfiddle` is non-trivially different from the pasted code by the way!!), I added some log information to it and commented out the second dispose (https://jsfiddle.net/xdjzek7z/) in which you see that the proxy subscription is disposed twice (or more accurately the subscription `dispose` method is called twice, but I believe there is a guard just like the one in `FinallyDisposable`). I will have to investigate because this behaviour puzzles me. It has no obvious effect, so it probably can be ignored but still.

Second remark, in the jsfiddle code, you dispose a subscription that is not related to the subject (`sub`). Why would the `proxySubscription` be also disposed?

I understand the problem as being, in : 

```
  const clickProxy = new Subject()
  const actions = intent({ ...sources, click$: clickProxy })

  const subscription = click$.subscribe(clickProxy)
```

How to dispose the subscription when `click$` terminates? Or is the problem a different one?

**Comment by whitecolor** [comment]
Yes by termnation with `dispose` I mean when subscription is disposed.
https://github.com/Reactive-Extensions/RxJS/issues/841

> I will have to investigate because this behaviour puzzles me

```js
var source = Rx.Observable.timer(0, 500)
.finally(() =>  {
  console.log('proxySubscription DISPOSE'); 
  proxySubscription.dispose()
})
let proxySubscription = source.subscribe(proxySubject)
let sub = source.subscribe(x => {
	console.log('source', x)
})
setTimeout(() => {
  console.log('DISPOSE')
	sub.dispose()
}, 1500)
```

It seems that `finally` callback is called on disposal of each subscription not on the last one.

> In any case, wrapping a solution into a simple function (no magic, no external dependency), in my opinion is the best approach if it is possible.

which function?

**Comment by brucou** [comment]
Alright, I get it now. It does call the `finally` callback twice, because `dispose` triggers as I said before a chain of upstream disposals. So basically `sub.dispose` triggers `proxySubscription.dispose()`, and the latter triggers again the corresponding chain of upstream disposals which is the same chain as the previous one. Anyways practical effects of double disposal are nil in principle, as Rxjs operators in principle guard against it.

> In any case, wrapping a solution into a simple function (no magic, no external dependency), in my opinion is the best approach if it is possible.
> which function?

Any function. I mean that finding a solution which allows to use a function is better than using a plug-in.

The question remains as to what is the desired unsubscription behaviour specification.

**Comment by whitecolor** [comment]
It is not double disposal. It is reaction on disposal of each indiviual subscription. And in my code there is no this things

> Any function. I mean that finding a solution which allows to use a function is better than using a plug-in.

This is discussed in othere topic https://github.com/cyclejs/core/issues/287#issuecomment-205846446
Without plugin you will have a messy code, but as it was mentioned by @staltz many times plugin is "experimental" solution and it would be nice if people **TO TRY** and express their opinion.

**Comment by brucou** [comment]
I can't try out the plugin in any case, I do not use babel. Can anybody make a nice short summary of the problem?

**Comment by whitecolor** [comment]
@brucou 
It is not only the problem of subject dispose, but also source stream completion. but `finally` solves both issues. dispose issue is actuall if you instanciatin cycle app multiple times, so when you call `dispose()` on `sources/sinks`.

**Comment by brucou** [comment]
@whitecolor Can you please update your code sample to be in line with the jsfiddle. It is really confusing (published 8 days ago). In the fiddle, the `finally` is on `source` not on `source2` and the difference is not small. Then, I am sorry to say I don't understand this `finally` solution. Yes, if your proxy observable terminates by itself, then the proxy subscription will be disposed. But, you trigger the proxy subscription disposal by disposing another subscription. Why not dispose directly the proxy subscription in the first place?? Is it necessary/mandatory to have a second proxy subscription to dispose the first proxy subscription?? Why the extra step?
In any case, is it not the same behaviour than the second proposed version of `circularSubscribe`? I will test it soon, and publish a fiddle, but I believe it should also cover both cases, proxy observable termination and subscription disposal. If that's indeed the case, I would personally prefer that solution as it also act as a marker of where I have a circular dependency. So maybe we have two alternative solutions here, which gives choice and choice is a good thing.

@ronag Could you have a look and see if the proposed `circularSubscribe` cover the use case?

**Comment by whitecolor** [comment]
@brucou filldle is not correct, code in post is correct, I've updated.

this shows how it is going on in cycle function:
```js
// you have some guy that want to subscribe to later declared `source`
// we use proxySubject for this
let source2 = proxySubject  
  .take(2) // say only will end in 2 steps

// you have some target timer source 
var source = Rx.Observable.timer(0, 1000)
.do(x => console.log('timer', x))

// this subscription will not be ended when source2 ends 
or subscriptions to it will be disposed
// so we will have a leak
let proxySubscription = source.subscribe(proxySubject)
```

**Comment by brucou** [comment]
alright, thanks for the details, I understand much better now. I'll have a look at it tomorrow.

**Comment by milankinen** [comment]
How about `loop` signal function? Pros: it's explicit
```js
export function loop(input$, main) {
  let lo = null
  const in$ = input$
    .merge(O.create(o => (lo = o) && (() => lo = null)))
    .doOnCompleted(() => lo && lo.onCompleted() && (lo = null))
    .share()
  const [out$, loop$] = main(in$)
  const lo$ = loop$
    .doOnCompleted(() => lo && lo.onCompleted())
    .filter(val => lo && lo.onNext(val) && false)
  return out$.merge(lo$).share()
}
```

And example usage:
```js
const initialText$ = O.just("Cheers").shareReplay(1)
  const vdom$ = loop(initialText$, text$ => {
    const vdom$ = text$.map(text =>
      h("div", [
        h("h1", text),
        h("button", "Click me!")
      ]))

    const click$ = DOM.select("button").events("click")
    const updatedText$ = click$.withLatestFrom(text$, (_, text) => text + "!")

    return [vdom$, updatedText$]
  })
```

If the `input$` gate distracts you, it can be easily removed:
```js
const loopp = main => loop(O.empty(), main)

  const vdom$ = loopp(text$ => {
    const vdom$ = text$.startWith("Cheers!").map(text =>
      h("div", [
        h("h1", text),
        h("button", "Click me!")
      ]))

    const click$ = DOM.select("button").events("click")
    const updatedText$ = click$.withLatestFrom(text$, (_, text) => text + "!")

    return [vdom$, updatedText$]
  })
```

**Comment by brucou** [comment]
Alright, I got back to the problem, and here is my proposed solution : [jsfiddle](http://jsfiddle.net/3nf3qgzg/)

**Comment by staltz** [comment]
:+1: to all this research material, folks, it's good that you're reporting while you go.

**Comment by tusharmath** [comment]
Basically what we need is a `coprophagus` function — :)
https://gist.github.com/tusharmath/86b37c3db77353b305547f88de949e30

**Comment by staltz** [comment]
I'm labeling this issue as a discussion, because xstream has built-in solution for this. But I'm not "closing" the comments, I still think this is a good discussion and resource to read/re-read.
