### ISSUE TITLE
Side effects in selectors?

### ISSUE THREAD

**Issue by ronag** [cyclejs/core#258]
What are the general thoughts on having side effects in selectors. 

E.g. if I wanted to create a driver against a database that send back a changes stream. How would I managed the subscribe/unsubscribe? Doing it in a selector is so easy but Im unsure whether there are any pitfalls?

e.g.
```javascript
select(query) {
   return db
      .changes(query)
      .takeUntil(db.reconnect$)
      .repeat()
}
```

In a pure sense this will cause a side effect...

The alternative which is much more complicated is to make some kind of reference counted subscribe/unsubscribe requests to the driver...

**Comment by staltz** [comment]
What do you mean with "selector"? Reminds me of CSS selectors.

> E.g. if I wanted to create a driver against a database that send back a changes stream.

We don't usually do that approach. Every read comes from sources and every write goes to sinks.

**Comment by ronag** [comment]
> E.g. if I wanted to create a driver against a database that send back a changes stream.
We don't usually do that approach. Every read comes from sources and every write goes to sinks.

Yes, the write goes to the sink. But in order to manage the READ changes stream from the database some requests needs to be made to the database.

**Comment by ronag** [comment]
e.g.

A lot of boilerplate

```javascript
function intent({ db }) {
   const dbValue$ = db.select(id)
   const dbRequest$ = Observable
     .of(id).flatMapLatest(id => ({ method: 'GET': id }))
     .concat(db.reconnect$.map(() => ({ method: 'GET', id }))

  return {
    ...
  }
}
```

vs:

```javascript
function intent({ db }) {
   const dbValue$ = db.select(id)

  return {
    ...
  }
}
```

**Comment by ronag** [comment]
So I guess the conceptual question is whether a `GET` request is actually a side effect.

We have the same problem with `DOM.select` which actually does have the side effect of adding event handlers onto the DOM.

**Comment by ronag** [comment]
I'm doing this properly using a helper method instead that sets put the request/response streams. 

Though I guess the conceptual question remains? Doesn't the `DOM.select` also perform side effects?

**Comment by staltz** [comment]
> Doesn't the DOM.select also perform similar side effects as subscribing to a database changes stream?

DOM.select().events() dosn't add more event handlers to the DOM, it's just a fancy `observable.filter()` because we use event delegation.
