### ISSUE TITLE
Remove .DOM boilerplate for Cycle DOM Components in Views

### ISSUE THREAD

**Issue by arlair** [cyclejs/core#261]
I have been working on some [Cycle UI](https://github.com/eldarlabs/cycle-ui) components and every component needing .DOM to render seems like a lot of boilerplate in the view that doesn't really add anything useful.

eg:
```
return div([
  h3('.example', [`Using Cycle-UI`]),
  Input(sources, {
      label: `Answer to life`,
      maxLength: 50,
  }).DOM,
  RadioButton(sources, {
    label: 'Radio easy',
    checked: true,
  }).DOM,
])
```

I am (trying ;) to use TypeScript and know the next version of Cycle.js is being rewritten to use TypeScript. I think it would make sense if there was a TypeScript interface for Cycle DOM Components. If it is a Cycle DOM Component, it knows to use the DOM property. It makes sense to render the DOM, or is there something else a Cycle DOM Component might do?

Perhaps in the current JavaScript version, just a check for a DOM property might suffice?

Any thoughts?

**Comment by staltz** [comment]
In general when we talk of "Cycle Components", we mean just a function that handles different sources and sinks. So far we don't have anything special treatment for "DOM-only" components.

**Comment by arlair** [comment]
I think I'm talking about modifying transposition.js in the DOM libraries.

cycle-dom seems to have some checks for function, VirtualText, VirtualNode, Widgets and Thunk.

cycle-snabbdom seems to check for object and function.

As a user, I would like to pass it a Cycle Component and get it rendered. This would make the view code consistent across any implementation of the target. At the moment I need to know to call .DOM for every DOM component.

In psuedocode something like:

```
if vTree is a CycleDomComponent (or CycleComponentNode, whatever the best term is to make it explicit what we are rendering)
  // return whatever is needed to render this component
  return Rx.Observable.just(vTree.DOM)
```

**Comment by whitecolor** [comment]
@arlair 
If you component returns only DOM sink you can just reutrn `vtree$` from it not `{DOM: vtree$}`. What you are proposing actually just make things obscrure.

**Comment by arlair** [comment]
@whitecolor I believed returning the vtree in DOM was the standard and did not think of your option. However, the components won't all necessarily return just a vtree,  so this would seem even more obscure to me ;) I feel it would be more error prone and mentally taxing to program that way. Library users would require knowledge about whether the DOM call is needed for each component in the library.

Modifying a component in the future would also break existing code if I modified the interface to return more than one sink. This might be easier to notice with TypeScript interfaces, but I think a runtime error for JavaScript.

**Comment by whitecolor** [comment]
It is explicit way of calling `input.DOM`is ok, no magic.

**Comment by staltz** [comment]
> However, the components won't all necessarily return just a vtree, so this would seem even more obscure to me

If the component has more sinks than just the `DOM` sink, then it shouldn't be placed in a vdom tree in the first place, because you will lose all other sinks when they are given to the vdom tree.
