### ISSUE TITLE
HTTP requests being executed multiple times

### ISSUE THREAD

**Issue by felipecsl** [cyclejs/core#262]
I'm trying to build a simple login form where, in the happy path, you type your email and password, click login, a network request is fired and a response is returned back with an auth token.
I got to the point where the request is fired after I click on the button, I get the token out of the response body and update the UI based on whether I got a successful response or not.
After a successful login I want to redirect the user to another page, which I'm also having trouble with, but I'll leave this for another time.

Based on the token received from the API, I need to both update the UI and store the token in the state. I've based off of [this project](https://github.com/kahlil/cycle-browserify-boilerplate) which helped me a in lot getting started.

Here is the part of the code where I'm having trouble:

`home-index.js`
```javascript
import view from './home-view'
import intent from './home-intent'
import model from './home-model'
import {Observable, ReplaySubject} from 'rx'

const Home = (sources) => {
  const {state$} = sources
  const actions = intent(sources)
  const token$ = model(sources.HTTP)
  const request$ = actions.map(data => ({
    url: '/auth',
    method: 'POST',
    send: Object.keys(data).map(k => k + '=' + data[k]).join('&')
  }))

  return {
    DOM: view(sources, token$),
    HTTP: request$,
    state$: token$,
  }
}

export default Home
```

`home-model.js`
```javascript
import {Observable} from 'rx'

const homeModel = (response$) => {
  return response$.flatMap(x => x)
      .map(res => res.body)
      .startWith({})
      .catch(e => Observable.just(e.response.text))
}

export default homeModel
```

`home-view.js`
```javascript
import {div, h1, h2, button, h, form, a} from '@cycle/dom'

const view = (sources, state$) => {
  const {router: {createHref}} = sources
  const portfolioHref = createHref(`/portfolio`)
  return state$.map(s => {
    if (s.token === undefined) {
      return div([
        h(`p`, s),
        form({autocomplete: 'off'}, [
          h(`paper-input.username`, { label: 'Username'}),
          h(`paper-input.password`, { label: 'Password', type: 'password'}),
          h(`paper-button.login`, { raised: 'true' }, `Login`)
        ]),
      ])
    } else {
      return div([
        h1(`Logged in!`),
        a(`.something`, {href: portfolioHref}, [`Portfolio`]),
      ])
    }
  })
}
export default view
```

My problem is that once I return `state$: token$` in order to update the store, the request is executed twice. Is there a way I can achieve this without having it get fired multiple times?
I've tried using `share()` but that didn't seem to work.

I've just started playing with Cycle, so please bear with me if I'm doing it competely wrong.

Thanks!

**Comment by felipecsl** [comment]
Maybe same root cause as #238 ?

**Comment by laszlokorte** [comment]
where did you put the `share()` ? You should put it into the model either here: `response$.flatMap(x => x.share())` or here `response$.flatMap(x => x).share()`

**Comment by felipecsl** [comment]
Yep, I tried putting it on the model, still get double requests.
Good "catch" about the `catch` :) thanks

**Comment by laszlokorte** [comment]
Have you checked if you `request$` stream does really issue only one request?

**Comment by staltz** [comment]
@felipecsl have you tried using `eager: true` on requests? or you can also enable it everywhere as a driver setting in `makeHTTPDriver`?

**Comment by felipecsl** [comment]
Interesting... `eager: true` fixed it. @staltz care to explain why is that? is that expected behavior?

**Comment by felipecsl** [comment]
It actually makes sense, since `eager` causes cycle-http to `replay` the inner `request$` and, based on the [docs](http://reactivex.io/documentation/operators/replay.html):

``` 
If you apply the Replay operator to an Observable before you convert it into a connectable Observable, the resulting connectable Observable will always emit the same complete sequence to any future observers, even those observers that subscribe after the connectable Observable has begun to emit items to other subscribed observers.
```

**Comment by kliron** [comment]
Thanks, this thread saved my sanity. I'm new to Rx and Cycle.js so I was suspecting I was doing something wrong in my code which I couldn't spot. I was seeing double or multiple requests from nested components while those requests that originated from my top-level components run fine. Using `eager: true` _only in the requests originating from the nested components_ corrected the issue. I'm not sure why this is the case. Could someone explain? The doubly sent requests where POSTs if that even matters.

**Comment by kikkiraj** [comment]
where we should set eager: true?

**Comment by staltz** [comment]
@kikkiraj The library has been updated a long time ago, now it's `lazy`, and it's described here https://cycle.js.org/api/http.html#api-makehttpdriver
