### ISSUE TITLE
Best practice for DOM side effects

### ISSUE THREAD

**Issue by deadbeef84** [cyclejs/core#266]
What is the recommended way of handling side effects for the DOM?

From what I can see there are two different types of DOM side-effects:
* Event related: `preventDefault(), stopPropagation(), stopImmediatePropagation(), event.dataTransfer, event.clipboardData` just to name a few
* Methods of dom elements: `focus(), blur(), click(), dispatchEvent()`

From my understanding, all these side-effects should happen inside a driver. Is there any official (or unofficial) driver that handles any of these side effects? In absence of such a driver, I'm currently putting all my side effects directly inside my component intents, eg. `DOM.select('.x').events('click').do(event => event.preventDefault())`. This feels a bit hackish.

Also, assuming there would be a driver for every side-effect, it seems a bit tedious and error-prone to have to forward and merge all these "side-effect-sinks" up from each and every component. This also means that parent-components needs to be aware of all the sinks that needs to be forwarded up the chain. Or is there perhaps a better way?

Related: #153 #202 #65

**Comment by dralletje** [comment]
A possible solution is either 1) having the DOM driver wrap something immutable around the events, or 2) having the DOM driver accept wrapped event.

1 would look like
```
DOM.select('.x').events('click').map(event => event.preventDefault()
```
Note the `.map` instead of `.do`, the actual side-effect will be executed in the driver.
This however requires to wrap the event, and I don't think that will go without breaking stuff/more maintenance.

2 would look like
```
DOM.select('.x').events('click').map(event => DOM.preventDefault(event))
```
where the DOM driver will 'unwrap' until it finds the actual event (so you could do multiple 'transforms' on the event) and will apply them. This may be harder to understand for people new to functional programming and composing, but it looks really good to me :grin:

**Comment by whitecolor** [comment]
Such things can be executed using `hooks`, LIke calling `blur`, snabbdom has very good hooks api.

**Comment by laszlokorte** [comment]
@dralletje you would still need a sink to accept that transformed stream, right? And that can not be the DOM sink.

Another more general approach would be a `methodCallDriver` accepting a stream of `{obj: ..., methodName: "foo", args: [1, "bar", true]}` objects.

**Comment by dralletje** [comment]
@laszlokorte not if it would be implemented **in the DOM driver!!!! :o**

**Comment by laszlokorte** [comment]
@dralletje Ok let's say we have this stream:
```
eventsToPrevent$ = DOM.select('.x').events('click').map(event => DOM.preventDefault(event));
```
How would we pass this stream to the dom driver?

**Comment by dralletje** [comment]
@laszlokorte yeah you're right, my bad, hahaha :-)

**Comment by whitecolor** [comment]
`DOM.select('.x').events('click').map(event => DOM.preventDefault(event))` 
this is still posiible, not very functional, but you can map this to resulting stream if you need.

**Comment by laszlokorte** [comment]
@whitecolor but then you would have to have `DOM.preventDefault()` cause the side effect so it would have no benefit over `.do(event => event.preventDefault())`

**Comment by whitecolor** [comment]
right

**Comment by ronag** [comment]
Also, how does this effect e.g. cycle-restart?

**Comment by staltz** [comment]
@deadbeef84 Check also this preventDefault driver https://github.com/cyclejs/examples/blob/master/autocomplete-search/src/main.js#L21

**Comment by ronag** [comment]
@staltz: That doesn't really help... should we have one driver for each possible method?

e.g.
```javascript
stopPropagation
blur
focus
preventDefault
etc...
```

Some of these fall into logical grouping e.g. the Clipboard and Drag And Drop Api's which makes sense to make drivers for.

**Comment by ronag** [comment]
Event side effects

```javascript
stopImmediatePropagation
stopPropagation
preventDefault
```

Might fit into something like:

`cycle-event`

But I'm unsure how to handle DOM side effects in a elegant way.

**Comment by staltz** [comment]
> cycle-clipboard
> cycle-dragndrop

That makes sense. But then again each of these drivers may be just one line of code. Also the blur or focus may be just one line Driver period. So I don't see the point in making library for it. Plus, if you need to do a lot of side effects, it sounds like something is wrong.

**Comment by ronag** [comment]
I think this is an issue not a discussion. Until there is a pragmatic practice for this I see this as a rather serious issue.

**Comment by whitecolor** [comment]
@ronag Coud you explain issue for what?

**Comment by ronag** [comment]
@whitecolor: 

```javascript
stopImmediatePropagation
stopPropagation
blur
focus
preventDefault
click
dispatchEvent
```

Creating separate drivers for all of these is not very pragmatic and will create unmanageable boilerplate to send around all those sinks. We have code now where we are sending around almost 20 sinks in a nested application, it's difficult to work with.

This is not an issue with `cycle-core`, it's more of a best practice/what's the plan issue.

**Comment by laszlokorte** [comment]
As I wrote earlier:

```es6
const methodCallDriver = (call$) => {
  call$.subscribe(({object, methodName, args = []}) => {
    object[methodName].apply(object, args);
  });
};

const main(sources) {
  return {
    DOM: ...,
    methodCall: DOM.select('.form').events('submit').map((evt) => ({
      object: evt,
      methodName: 'preventDefault',
    })),
  };
};
```

you could even restrict it to only allow some method calls:

```
const makeMethodCallDriver = (allowedNames) => {
  return const methodCallDriver = (call$) => {
    call$.subscribe(({object, methodName, args = []}) => {
      if(allowedNames.indexOf(methodName) < 0) {
        throw `Method ${methodName} is not allowed to be called via driver`;
      }
      object[methodName].apply(object, args);
    });
  };
};
```

**Comment by whitecolor** [comment]
Of couce you don't need to have driver for each possible "move". That is always concise design choise. Its good idea to combine in one driver related (a like) things that share the same code and have the same nature.

**Comment by laszlokorte** [comment]
The key is that all of these
```
stopImmediatePropagation
stopPropagation
blur
focus
preventDefault
click
dispatchEvent
```
are just method calls that need no further context. The object they are called on in available inside the application as well as the method name and the parameters. And they do not have any rich semantics for which you would want to design a designated API. So I see no problem with handling them all inside one simple driver.

**Comment by deadbeef84** [comment]
@staltz I think the link you provided (https://github.com/cyclejs/examples/blob/master/autocomplete-search/src/main.js#L21) actually highlights the problem. In the example a **very** specific driver is created, one that not only preventDefault() but **also set focus if the event type is 'blur'**. If there was an official solution to handle this, _hacks_ like this wouldn't be necessary.

Also, I think this forces everyone to create their own drivers for handling a very common use case. Eventually we will have projects with side effects directly in their intents (like I'm currently doing :-1:) or lots of different implementations of an event-driver doing pretty much the same thing which is also not very nice. I would expect this to already be solved by the framework, perhaps by `cycle-dom`?

**Comment by staltz** [comment]
What solution do you exactly suggest?

**Comment by whitecolor** [comment]
> Also, I think this forces everyone to create their own drivers for handling a very common use case. 
You can come up with a ready driver, for fabric like that https://github.com/whitecolor/cycle-async-driver

**Comment by btipling** [comment]
Interesting discussion. One aside comment is that when you link to source code, please link to it with the canonical form (by pressing y on the file) so that the links aren't dead when code is moved.

https://github.com/cyclejs/cyclejs/blob/c4d239f2ec6a8db4ce44a2d88420d3110450c216/examples/autocomplete-search/src/main.js
