### ISSUE TITLE
Add an example where multiple components are used with isolate()

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#269]
See [this comment](https://github.com/cyclejs/core/issues/259#issuecomment-196421324): 

> very few of the examples use isolate (only those that strictly require it), and all of these examples call isolate right before using a component, rather than when defining the component as the doc suggests.

- - -

I'd be glad if someone would submit a PR for cycle-examples to add one example with a multi-level hierarchy of components, and the usage of isolate().

The example should be as small as possible, as *vanilla-Cycle.js* as possible, but still large enough to illustrate the idea of multiple components and how they are composed. The BMI example is the smallest case, and the most natural example, but we need something like that, just a tiny bit bigger.

Volunteers? @Cmdv @chadrien?

**Comment by Cmdv** [comment]
@staltz I can pick it up after finishing up on https://github.com/cyclejs/dom/pull/110

**Comment by staltz** [comment]
:+1: I'll review that one

**Comment by Cmdv** [comment]
cool still having issues with getting my implementation to curry more than just twice but I'll hit you up when I have something worth looking at :)

**Comment by Cmdv** [comment]
@staltz where would you like this to live in `cyclejs/examples` ? just thinking about what would be useful example, don't want to make it too complex with things like routing! (thinking out loud)

**Comment by staltz** [comment]
Yes it could live in `cyclejs/examples` in some new dir. I dont feel creative now, but one initial suggestion is to solve the component hierarchy of this React example http://facebook.github.io/react/docs/thinking-in-react.html but I feel like that example is too shallow because just one component is actually receiving user intent.

**Comment by Cmdv** [comment]
Cool, @TylorS came up with a good idea of doing the `click here to add a new button`and each child button created has the same functionality.

**Comment by staltz** [comment]
ok sounds like a good plan, I can help with guidance once we have something concrete

**Comment by jamesrhaley** [comment]
I have a naive example of a range slider with inputs that calculate a range.  It doesn't use isolate but needs something of that nature to get rid of the boiler plate.  My premise is a child component is its intent and its view and a parent load those, computes the model, and returns a rendered view. https://github.com/jamesrhaley/nested-cycle

```
fun child(driver, props):
    return {
        intent from driver,
        view with props
}

fun parent(driver, props) {
  let all = child(driver, props)
  let state$ = model(all.intent)
  let vtree$ = view(all.view)
  return {
    driver: vtree$
  }
}
```
I would love feed back.  Props is currently an object when it probable needs to be an Observable.

**Comment by Cmdv** [comment]
Hi @jamesrhaley have you tried sharing your link on the [gitter channel](https://gitter.im/cyclejs/core)?

You are more likely to get help there as these are really open for technical bugs and issues :)

**Comment by staltz** [comment]
I think this issue is now done with `nested-folders` in the examples repo.
