### ISSUE TITLE
Fix broken website layout

### ISSUE THREAD

**Issue by salutis** [cyclejs/core#274]
_Issues are disabled for `cyclejs.github.io` so I'm reporting this issue here._

The website (http://cycle.js.org) is all over the place on my 4-inch iPhone.

**Example:**

<img src="https://cloud.githubusercontent.com/assets/1158274/13886420/0dd38754-ed37-11e5-857e-f06e4c6c40c4.PNG" width="320" height="568"/>

**Another example:**

<img src="https://cloud.githubusercontent.com/assets/1158274/13886583/d10dc536-ed37-11e5-8f1c-29a04a5ef60b.PNG" width="320" height="568"/>

**Comment by guacjack** [comment]
https://github.com/cyclejs/cyclejs.github.io/pull/54
