### ISSUE TITLE
Why do website examples of DOM use 'attributes

### ISSUE THREAD

**Issue by SteveALee** [cyclejs/core#282]
The 1st example on http://cycle.js.org/ and others use 'attributes in the attribute' object. This appears to be redundant and I have seen no other examples using this. Is it purely historical?

<pre>
input('.field', {attributes: {type: 'text'}}),
</pre>

Apparently with snabbdom you have to use attrs or props, you can’t just pass the attributes directly as the second argument.

**Comment by whitecolor** [comment]
Property is that can be set on the DOM element itself `input.value = 1`. attribute is that should be set with `input.setAttribute('type', 'text')`. In snabbdom there was mad clear distinction, API is a little bit verbose. I had an issue on that https://github.com/paldepind/snabbdom/issues/83

**Comment by SteveALee** [comment]
So here is not always a 1 to one properties to attributes? We thought so but unable to find a clear list of the differences. Thanks

**Comment by whitecolor** [comment]
some props maybe set on elements and they do not set any attributes for example `el.innerHTML = 'xxx'` does not set any attributed, but does something else. And attributes are attrubtes `el.setAttrubte("data-sectect", 'xxx'`)` will set `data-secret` attribute on the element.

**Comment by SteveALee** [comment]
Though I think your data-secret example would normally be accessed as el.dataset.secret?

**Comment by SteveALee** [comment]
Thanks for the answer. I'll close as now understand better.

**Comment by whitecolor** [comment]
> Though I think your data-secret example would normally be accessed as el.dataset.secret?
It seems not in IE prior 11)

**Comment by SteveALee** [comment]
Wow, yes. This isn't new. More concerning is not Opera Mini.

**Comment by SteveALee** [comment]
For completeness this article is [a good explanation](http://javascript.info/tutorial/attributes-and-custom-properties)

> You should use attributes in only two cases:

> 1.  A custom HTML attribute, because it is not synced to DOM property.
> 1.  To access a built-in HTML attribute, which is not synced from the property, and you are sure you need the attribute.
>    For example, value in INPUT.
