### ISSUE TITLE
Sequential composition of the functions/components

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#283]
Think this is one of the common situation maybe later might go to some faq.
I have two functions that should be executed in one after another `Login` and `GoToPage`:

I might do it this way:
```js
import Login from './Login'
import GoToPage from './GoToPage'

function main(){
  const login = Login({...})
  const goToPage = login.success$
    .map(_ => GoToPage({...}))

  return {
    DOM: goToPage.flatMap(_ => _.DOM)
  }
}
```

But here I don't like that to get `DOM` sink from `GoToPage(..)` I have to use `flatMap`, and that the `GoToPage` will not be "executed" at zero moment.

Another variant would be to go with such approach:
```js
import Login from './Login'
import GoToPage from './GoToPage'

function main(){
  const login = Login({...})
  const goToPage = GoToPage({...})

  return {
    DOM: goToPage.DOM.sample(login.success$)
  }
}
```

What do you think about this pattern and solutions? I believe the first is more of "imperative style", and second is more of "functional". Any other options to compose this?

**Comment by ronag** [comment]
In our application we do it like this:

```javascript
import Login from './Login'
import GoToPage from './GoToPage'

function main({ login }){
  const page$ = login$
    .success$
    .startWith(false)
    .switchMap(result => result ? Login({...}) : GotoPage({...}))
  return {
    DOM: page$.switchMap(page => page.DOM)
  }
}
```

**Comment by whitecolor** [comment]
@ronag Ok it think it is fair to execute Login/GoTo only when needed.

**Comment by laszlokorte** [comment]
You could do something like:

```es6
function main() {
  const loginPage = Login({...})
  const goToPage = GoToPage({...})

  return {
    DOM: O.combineLatest(
      login.auth$, loginPag.DOM, goToPage.DOM, 
      (auth, login, page) => auth ? page : login
    ),
  }
}
```

In my application I try to keep the subscriptions to the observables of components alive most of the time in order to not lose state accumulated by `scan`. It also keeps the nesting depth of observables low.

**Comment by whitecolor** [comment]
@laszlokorte 
but here you will build `loginPage.DOM` and `gotToPage.DOM` tree, even if not needed, you just don't care about exessive computations in this particular case?

**Comment by laszlokorte** [comment]
Yes that's right. I do not care about that in the most cases. In cases in which the creation of the vtree of a component is really expensive I wrap it into a lazy closure thunk object anyway.

**Comment by whitecolor** [comment]
> wrap it into a lazy closure thunk object anyway

Do you have code to share?

**Comment by laszlokorte** [comment]
```

const CacheThunk = function thunkConstructor(key, fn, debug = false) {
  this.key = key;
  this.fn = fn;
  this.debug = debug;
};

CacheThunk.prototype.type = "Thunk";

CacheThunk.prototype.render = function thunkRender(previous) {
  if (!previous || previous.key !== this.key) {
    if (this.debug) {
      console.log("cache busted: " + this.debug);
    }
    return this.fn();
  } else {
    return previous.vnode;
  }
};

// The constructor for simple virtual-dom Thunk object
// prevents DOM updates of child nodes until the cache key
// changes and creates the new child nodes lazyly.
//
// key - the cache key or an array of cache keys
// fn - the function that returns the child nodes
// debug - an optional string that get's logged to the console
//         whenever the cache invalidates.
export default (key, fn, debug) => {
  return new CacheThunk(fn, key, debug);
};
```

Usage:
```
const view = (state$) =>
  state$.map((state) => { 
    return cache(state, () => render(state))
  })
;
```

**Comment by whitecolor** [comment]
laszlokorte :+1: thanks
