### ISSUE TITLE
Add cycle.js to DefinitelyTyped

### ISSUE THREAD

**Issue by dmitriid** [cyclejs/core#286]
A low priority feature request.

Add cycle.js (and other cycle.js-related projects) to https://github.com/DefinitelyTyped/DefinitelyTyped (the home page for the project is http://definitelytyped.org).

Some tools (notably, IntelliJ IDEA) support these definitions to provide better code insights.

**Comment by staltz** [comment]
Hi, thank you for taking your time to send us this issue. We appreciate it, however we are already in the process of rewriting Cycle entirely in TypeScript, which will fulfill this need. So that's why I'll close this issue.

**Comment by LukaJCB** [comment]
Hi, This might not be the best place to say this, but I'm a big fan of Cycle and would love to be able to use it with Typescript ASAP and therefore I'd also love to contribute to . Now I've checked out the Typescript branch, but the latest commit was from June 2015. Am I missing something? Where do I start? Would appreciate any help!

**Comment by staltz** [comment]
Check #196 for the overall progress in this direction. If you want to help, clone the cycle-dom repo, checkout the `diversity` branch, then try to make one more test pass, then submit a PR. One PR per test. I myself will be doing this next week too. The typescript branch is old, deprecated.

**Comment by dmitriid** [comment]
Awesome! I'll see if I can help!

**Comment by kylecordes** [comment]
@staltz What is your advice for people picking up cycle today, who want to use typescript? Wait for the upcoming typescript version? Set aside typescript and use cycle with plain ES6? ES5?

**Comment by staltz** [comment]
Use ES6 today. It won't be too hard to convert ES6=>TS.

**Comment by kylecordes** [comment]
Thanks. I just got an example project up and running with Cycle, ES2015, and Rollup. But I miss TypeScript already...

**Comment by LukaJCB** [comment]
@staltz Just finally got around to running those tests, but it seems you're already done? Next step would be HTTP?

**Comment by staltz** [comment]
Yes

**Comment by arlair** [comment]
@kylecordes if you are feeling brave, you could try this starter project that uses TypeScript with the current Cycle.js https://github.com/eldarlabs/cycle-ui-typescript-webpack, or just pick bits from it to add to your own project.

**Comment by kylecordes** [comment]
I had not seen that starter project, but I have thought about this picking up the current cycle with typescript. But I put together these bits:

* @staltz has a strong appreciation of typescript.
* He is working on a new version of cycle, and typescript.
* He appears to be a rather productive developer.
* It seems to be taking some time.

Taking that information jointly, I conclude that the new cycle will be considerably different than just taking the current cycle and applying types around it. Presumably if the plan were to rename the files .ts, adjust the imports for typescript syntax and idiosyncrasies, and ship, then it would be done by now. Therefore I assume that the shape of Cycle and its is changing somewhat, and that I probably don't want to dig into the pre-typescript version much.

**Comment by staltz** [comment]
> Taking that information jointly, I conclude that the new cycle will be considerably different than just taking the current cycle and applying types around it. Presumably if the plan were to rename the files .ts, adjust the imports for typescript syntax and idiosyncrasies, and ship, then it would be done by now. Therefore I assume that the shape of Cycle and its is changing somewhat, and that I probably don't want to dig into the pre-typescript version much.

For users of Cycle.js, the new version will be mostly backwards compatible, so don't be afraid of using the current online version.

**Comment by QuantumInformation** [comment]
@staltz as a proponent of TS, I was wondering what was your biggest motivating factors for migration to TS for cyclesjs?

**Comment by staltz** [comment]
http://staltz.com/all-js-libraries-should-be-authored-in-typescript.html

**Comment by QuantumInformation** [comment]
ah good points!
