### ISSUE TITLE
svg hyperscript helpers in Cycle DOM 

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#288]
SVG should be writable not only through hyperscript but also hyperscript-helpers, where SVG-specific elements like `<g>` and `<a>` could actually be attached as hh functions on the hh function `svg`, e.g.:

```js
svg([
  svg.g(
    ...
  )
])
```

Which supports also destructuring.

**Comment by Kriegslustig** [comment]
Are you already working on this? I'd love to help otherwise :)

**Comment by staltz** [comment]
Done now thanks to https://github.com/cyclejs/dom/issues/118
