### ISSUE TITLE
"Double" class based isolation is broken

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#290]
This is the case where isolated vtree$ gets again "isolated" on the same root element:
```js
let Child = ({ DOM }) => {
  const click$ = DOM.select('.click')
    .events('click')
    .scan(a => a + 1, 0)
    .startWith(0)
  return {
    DOM: click$.map(x => div(div('.click', 'clicks: ' + x)) )
  }
}
let Parent = ({ DOM }) => {
  return {
    DOM: isolate(Child)({DOM}).DOM
  }
}
let main = ({ DOM  }) => {
  return { DOM: isolate(Parent)({DOM}).DOM }
}
run(main, {
  DOM: makeDOMDriver('#app')
})
```
There will be resulting markup:

```HTML
<div class="cycle-scope-cycle2 cycle-scope-cycle1">
  <div class="click">clicks: 0</div>
</div>
```
Because of this:
https://github.com/cyclejs/dom/blob/master/src/render-dom.js#L164
element will be mached with such selector: `.cycle-scope-cycle2 .cycle-scope-cycle1 .click` but should be with `.cycle-scope-cycle2.cycle-scope-cycle1 .click` (without space)

And `click` event in `Child` won't work.

I believe this issue https://github.com/cyclejs/core/issues/277 was created due to this bug.
And probably this will solve it https://github.com/cyclejs/core/issues/226

**Comment by staltz** [comment]
This should be now fixed in Cycle DOM v10 (release candidate), I recommend trying it out

**Comment by tusharmath** [comment]
@staltz it would be great if you could may be apply the patch for the current stable release.

**Comment by whitecolor** [comment]
I think there won't be patch for this version, use `npm i @cycle/dom@canary -S` and then plug it with wrapper in to old core:

```js
// transposition is optional
DOM: (vtree$) => makeDOMDriver({transposition: true})(vtree$, rxAdapter)
```

**Comment by staltz** [comment]
If the bug persists in Cycle DOM v10+, we can reopen.

**Comment by whitecolor** [comment]
It should not.
