### ISSUE TITLE
DOM event simulateBubbling not correct for non-bubbling events

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/core#291]
@wand3r posted this in twitter: https://gitter.im/cyclejs/core?at=5705714df5db499c02183f0c

I simplified the case a bit:

**Classical DOM:**
http://www.webpackbin.com/N1y4B5k1W
**CycleJS:**
http://www.webpackbin.com/NydbM5JkZ

**Description**
Move your cursor in and out of the inner (blue) div but keep it in the yellow div.

In the classical DOM case you wont see `mouseenter` and `mouseleave` events being triggered because those events to not bubble. They occur on the inner (blue) div but the listeners are attached to the outer (yellow) div.

In the CycleJS case you see those events being triggered even though `.select('#div1').events('mouseenter')` does also only specify the outer div.

The reason is that the dom drivers event delegation attached the listener for the capturing phase. This is required to receive non-bubbling events at all. Because of this the listener receives both the events of the inner and of the outer div.

The "wrong" behavior is now cause by `simulateBubbling`. it walks up the DOM tree starting at the event target and emits the event on all streams whose selector matches any ancestor. During this the `.select('#div1').events('mouseenter')` streams will receive the event because the `#div1` selector matches a parent of the `event.target` element. This is not desired because classically the `mouseenter` and `mouseleave` do not bubble up to parent elements.

**Solution**
The solution is to disable simulateBubbling walking up the tree for all non-bubbling events. For non-bubbling events only the stream which selected the `event.target` element itself should be notified.

**Comment by TylorS** [comment]
Thats for the issue @laszlokorte I'll try to get a fix out soon

**Comment by TylorS** [comment]
This should be fixed! :)
