### ISSUE TITLE
Special keywords for npm

### ISSUE THREAD

**Issue by jmeas** [cyclejs/core#292]
Drivers/components are an important part of the Cycle.js ecosystem. Yet finding community libs isn't particularly easy at the moment.

One thing that lots of tools use is to promote usage of a particular npm keyword for their packages. This can help developers find those tools, or power search pages on the project's site itself.

I think a similar system could work well for Cycle.js drivers and components.

Prior art:

- [Grunt plugins](http://gruntjs.com/plugins)
- [Gulp plugins](http://gulpjs.com/plugins/)
- [Yeoman generators](http://yeoman.io/generators/)
- [Ember Addons](https://www.emberaddons.com/)

If y'all think this is a good idea, I think the next steps could be:

1. decide on a keyword (`cyclejs-driver`/`cyclejs-component`, for instance)
2. promote it on the website in the proper section
3. either link to an npm search, or build your own search on the site

Cycle.js seems cool – I'd like to see the community around it grow, and this could help with that.

---

Also, without a special keyword, it can be tedious for community members to build discoverability around their modules. It requires adding [a whole bunch of permutations](https://github.com/jmeas/cycle-connection-driver/pull/7/commits/a5c321a11ec247a25f3bbc21c8c98ce6069e340c), which seems silly and isn't as useful as having one "official" keyword.

**Comment by brodybits** [comment]
More prior art: https://cordova.apache.org/plugins/ (powered by npmsearch)

**Comment by chadrien** [comment]
All drivers aren't listed there, but [awesome-cycle](https://github.com/vic/awesome-cyclejs#drivers) is a good start to find cycle related stuff (including drivers).

**Comment by staltz** [comment]
Because `cycle` is not good for search engines, let's use `cyclejs` (like the GitHub org) and Cycle.js in other texts, like in conference talks, etc. Drivers and libraries could be named just `cycle-foo`, as they already have been.

**Comment by jmeas** [comment]
@staltz sounds good. So – just to clarify – you don't think it's valuable to use npm keywords as a means to power a search page on a site? My recommendation was only referring to npm keywords and the value that they bring, not names of libraries or conference talks, etc.

**Comment by staltz** [comment]
Unfortunately Cycle packages at `@cycle/foo` can't even be searched on npmjs.com because NPM still hasn't built search feature for scoped packages.
