### ISSUE TITLE
Implementing a CouchDB Driver

### ISSUE THREAD

**Issue by ronag** [cyclejs/core#293]
I'm looking into how to implement a CouchDB driver using PouchDB (https://pouchdb.com).

Most things are pretty clear and easy to implement. Except for one thing, the changes streams (https://pouchdb.com/api.html#changes).

The obvious way to implement it is something like the following:

```javascript
return {
   changes(opts) {
      return makeObservableChanges(db.changes(opts))
   }
}
```

However, the problem with this is that `db.changes` actually is a `GET`side effect, which kind of goes away from the cyclejs best practices as I know them.

Does anyone have any advice on how to go about this?

**Comment by ronag** [comment]
I haven't quite been able to follow this discussion (https://github.com/cyclejs/core/issues/278) but it might be related?

**Comment by whitecolor** [comment]
> However, the problem with this is that db.changes actually is a GETside effect, which kind of goes away from the cyclejs best practices as I know them.

What best practices do you mean?

Basically you have async request/response pattern in you drivers and want to return metastrem of responses? Then just attach there `changes` method which will be used for reading changes from driver. And don't forget to `cancel` them on stream end and driver `dispose`.

**Comment by ronag** [comment]
@whitecolor: Sorry but I didn't understand any of that...

**Comment by whitecolor** [comment]
Selector method is just a connection point to driver from where streams come, side effects happen inside the driver.

By `sync request/response` I mean driver that takes request and returns async requests (like HTTP driver does).

**Comment by ronag** [comment]
@whitecolor: The problem here is the returned stream doesn't have an end like HTTP responses would have...

**Comment by whitecolor** [comment]
@ronag 
DOM driver to doen't have "end", it is just not monadic part of the driver, I have such driver that combines both https://github.com/whitecolor/cycle-sqs

**Comment by ronag** [comment]
@whitecolor: This is where I have trouble, the `poll` method will have side effects. Shouldn't you have a `request` that starts the polling?

**Comment by whitecolor** [comment]
Compare to DOM driver events. It is the same situation. Its push, by calling `pool` `listen`, `.events()` you just attach to the source for push notifications.

**Comment by ronag** [comment]
I know I'm being difficult here and I appreciate the patience. I find this counterintuitive considering many past discussions here.

According to my understand you can't compare it to DOM driver event subscriptions since they only cause side effects WITHIN the application not against e.g. a server.

Again, with that reasoning the current HTTP driver interface makes little sense to me, i.e. why not simply have a `get` method instead of going through `request$`

**Comment by whitecolor** [comment]
Such issue about HTTP was discussed https://github.com/cyclejs/core/issues/278 but it can work out for some "static" point they, underneath in the driver there will be pull mechanics (for example long pooling) but it doen't metter -for application it will be incomming push messaging.

> According to my understanding you can't compare it to DOM driver event subscriptions since they only cause side effects WITHIN the application not against e.g. a server.

It is worth to think out of the "box of your front end application", DOM events is no difference to server, database events, or any other events. In you case by calling `changes` you subscribe to events stream from couch database.

**Comment by WorldMaker** [comment]
Maybe this will help. I haven't felt a need to refactor my Pouch work into a driver explicitly, but I did try to follow some best practices. Here's my Pouch Changes function:

```ts
export function pouchChanges$(db: PouchDB, options?: PouchChangesOptions) {
    return Rx.Observable.create(observer => {
        let changes = db.changes(options)
            .on('change', change => observer.onNext(change))
            .on('complete', info => observer.onCompleted())
            .on('error', error => observer.onError(error))
        return () => changes.cancel()
    })
}
```

The key difference between this version and what's posted above (other than the obvious fact that this is semicolon free Typescript) is that `Rx.Observable.create` creates a "cold" observable, which doesn't actually call `db.changes()` until it goes "hot". (It also handles cancelling the changes call on unsubscribe/dispose/completion.)

Maybe something like this is what you've been looking for?

**Comment by ronag** [comment]
@WorldMaker: That is basically the same as I wrote in the original question. It still has the same problem with side effects being performed outside of driver requests.

**Comment by ronag** [comment]
@whitecolor 

> It is worth to think out of the "box of your front end application", DOM events is no difference to server, database events, or any other events. In your case by calling changes you subscribe to stream of events from couch database.

Following @staltz stance on this, as I understand it, there IS a difference between DOM events and server, database events. DOM events happen INSIDE the application while server, database etc. happen outside the application.

**Comment by WorldMaker** [comment]
@ronag At which point I'm wondering if maybe you are being too self-imposed strict in your view of how this should work? Admittedly, part of why I've kept it factored as something other than a driver is because I'm maybe not strict enough. I quibble a bit at "basically the same" as my version at least restricts the surface area of the side effect at least to the length of observation (from start of observation to end of observation). If you were to, say, make a requests stream of a db name and options objects (`PouchChangesOptions`) you'd want to `flatMapLatest` to something more like this `Rx.Observable.create` than what you have in the top post.

**Comment by whitecolor** [comment]
> Following @staltz stance on this, as I understand it, there IS a difference between DOM events and server, database events.

I'm not sure you are following. DOM is environment where side effects happen, server is environment where side effects happen. Both guys are from **outside** world for your `main` function. No difference between two in terms of ability to perform side effects. You are creating problem for yourself on level ground.

**Comment by ivan-kleshnin** [comment]
@WorldMaker with **PouchDb** do we still need to have in-memory (reactive) cache or the database itself serves this purpose? I imagine in the first case syncs are still the problem.

**Comment by WorldMaker** [comment]
@ivan-kleshnin PouchDB still take IO time to save/retrieve. By default it's using HTML5 IndexedDB which can be fairly quick, but there's no guarantee, and it's just as likely it could be storing to WebSQL or SQLite or some other storage. Additionally, every time you save the DB creates an additional revision so autosaving can quickly bloat the DB if you are not careful.

**Comment by ivan-kleshnin** [comment]
@WorldMaker thanks. 

> Additionally, every time you save the DB creates an additional revision so autosaving can quickly bloat the DB if you are not careful.

So data is immutable and kept with a history.
So we can skip history tracking in the memory at least?!

Is your overall experience positive? Would you recommend to invest time in that?
I was thinking graphQL is the only (scalable) solution (though never liked it) but recently realized there are a plenty of competitor approaches.

**Comment by WorldMaker** [comment]
@ivan-kleshnin Sorry for late response. PouchDB stores data with some history, yes, but it's not immutable (it can/will be garbage collected; by default all of it won't synchronize between databases, just the most recent states). You can use it's history tracking for things like undo states and similar, and you need its history for collision solving in syncs, but don't expect Pouch to be a full "source control". You could probably skip some history tracking in memory, yes.

Overall, I've been happy with PouchDB in my projects that have been using it.

**Comment by ivan-kleshnin** [comment]
@WorldMaker thanks! I've already evaluated PouchDb and it does not satisfy my requirements. 
The only benefit is auto-sync with a huge line of limitations following. 
I think Pouch is good for particular kind of apps but far from being universal (which I expected).
