### ISSUE TITLE
successful and failed helpers for HTTP

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#297]
As proposal. Sometimes it is need need to handle errors and success separately, so then you may do:

```js
// get flat non interrupting stream of errors
let error$ = HTTP.flatMap(r$ => 
  r$.skip().catch(e => O.just(e))
)

// get flat non interrupting stream of success
let success$ = HTTP.flatMap(r$ => 
  r$.catch(O.empty())
)
```

Maybe this should be encapsulated into driver helpers:

```js
// get flat non interrupting stream of errors
let error$ = HTTP.failed(/* could take mapping function for error */)

// get flat non interrupting stream of success
let success$ = HTTP.successful(/* could take mapping function for response */)
```

Also would make possible such:
```js
// get flat stream of errors
let error$ = HTTP.select('users').failed()

// get flat stream of success
let success$ = HTTP.filter(r$ => /users/.test(r$.request.url)).successful()
```

To allow such usage:
```js
let successOfFiltered$ = HTTP.filter(r$ => ...).successful()
```
there probably a need to *proxy* methods like `map`, `filter` on the `response$$` to save this helpers, I would also save this way `isolateSink`, `isolateSource`, because they are lost too after `filter` or `map`.

wdyt?

Originally where proposed `getSuccess` and `getError` helpers.

**Comment by staltz** [comment]
@whitecolor Let's give it a try. Instead of attaching it to the HTTP source, let's have them as standalone functions, which can be imported. Release it as a small library and let's see how people feel when using it.

**Comment by whitecolor** [comment]
You mean imported and attached like this:
```
import {attachToDriver} from 'some-driver-helpers'
...

let httpDriver = makeHTTPDriver()
attachToDriver(httpDriver)
```
?

**Comment by staltz** [comment]
No, I mean

```js
import {successful, failed} from 'some-module-for-driver-helpers'
...
let error$ = failed(HTTP.select('users'))
```

**Comment by whitecolor** [comment]
Ok I get you.

**Comment by whitecolor** [comment]
Ok I get you. Though I'm not sure how this should be called)

**Comment by laszlokorte** [comment]
@whitecolor rx-maybe, rx-railway, rx-flatcatch?

**Comment by whitecolor** [comment]
I have implemented this methods in my driver factory, and they can be used from there
https://github.com/whitecolor/cycle-async-driver/#filtering-helper-select

It can be used as @staltz proposed or can be attached to driver source
```js
HTTP
 .select({method: 'POST', url: /users/})
 .filter(...) // helpers will are available after filter, and other stream transform methods as well
 .successful((res, requests) => res.body)
```

**Comment by staltz** [comment]
How about instead of attaching, you leverage `let` (RxJS) or `compose` (xstream)?

```js
HTTP
 .select({method: 'POST', url: /users/})
 .filter(...) 
  // helpers will are available after filter, 
  // and other stream transform methods as well
 .compose(successful((res, requests) => res.body))
```

**Comment by whitecolor** [comment]
Attaching allows to keep fluent API, but variant with let and compose are definitely better then:
```
import {successful, failed} from 'some-module-for-driver-helpers'
...
let error$ = failed(HTTP.select('users'))
```
I will implement it.

**Comment by whitecolor** [comment]
I add this ability to use it in either way https://github.com/whitecolor/cycle-async-driver#external-use-of-helpers-with-other-async-drivers

So it can be this way:
```
import {select, successful, failed} from 'cycle-async-driver'
...
select(HTTP, {method: 'POST', url: /users/}) // select helper to can be used
 .filter(...) 
 .let(successful) // will get all successful (without mapping)
```

**Comment by whitecolor** [comment]
I wonder what you think about the default names of such helpers, possible variants:
* `successful` and `failed`
* `success` and `failure`
* `success` and `fail`
* `succeed` and `failed`

**Comment by whitecolor** [comment]
Released it, chose default names `success` and `failure`.

**Comment by staltz** [comment]
Good stuff @whitecolor. I think we should have more initiatives like this for experimentation, which we release as a separate library, the community uses until it becomes a popular solution, and then we can make it official.

I suggest now to add this to awesome-cycle repo.

**Comment by staltz** [comment]
Also, I'll close this issue just because otherwise it would look like it's still not done. If/when we want to put it in HTTP driver, we can reopen this issue.
