### ISSUE TITLE
Isolate to support numbers for scoping

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/core#298]
Why is there are hard restriction on the type of scoping param in `isolate`? I think passing numbers for scoping should be allowed.

Calling `toString()` every where doesn't feel very intuitive.

**Comment by staltz** [comment]
We could add conversion to string inside `isolate`. What do you think @TylorS @laszlokorte ?

**Comment by TylorS** [comment]
That seems okay to me

**Comment by whitecolor** [comment]
`isolate(dataflow, '' + id)`

**Comment by staltz** [comment]
Fixed in isolate v1.4.0
