### ISSUE TITLE
manually triggering an event

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/core#300]
I wonder how we can manually trigger an event. For instance I want to fire a `submit` when has typed four letters in a text box.

**Comment by staltz** [comment]
I think you can make a small `submit` driver, that takes a stream of DOM elements as a sink, e.g. `sink.subscribe(element => { element.submit(); })`

As a similar example, see the preventDefault driver: https://github.com/cyclejs/examples/blob/master/autocomplete-search/src/main.js#L8

**Comment by edge** [comment]
Expanding on what @staltz said, here's a contrived example of the actual component.

```js
function SmartTextbox({ DOM }) {
    let text$ = DOM.select('.Textbox')
        .events('input').pluck('target', 'value');
    let submit$ = text$.filter(x => x.length === 4);
    return {
        DOM: text$.map(text => input('.Textbox', text)),
        submit: submit$
    };
}
```

**Comment by tusharmath** [comment]
Ah, a custom driver. Shouldn't it be a part of the DOM driver? Would it make sense to send a pull request?

**Comment by staltz** [comment]
Good idea @tusharmath, but before anything is added to the DOM Driver, it is better that it is first experimented as a separate community library, until we agree that it is worth putting in the DOM package.
