### ISSUE TITLE
@cycle/dom@10.0.0-rc13 events not working

### ISSUE THREAD

**Issue by ntilwalli** [cyclejs/core#303]
I updated to the latest rc and it's not working (http://www.webpackbin.com/4yza792lZ).  If you switch it back down to rc-8 it works

**Comment by staltz** [comment]
And also this bug: https://github.com/cyclejs/dom/commit/5ecdfebc86459d9c463d81e762a04db9e2e624c5#commitcomment-17340230

**Comment by ntilwalli** [comment]
Cool  The compile error got fixed when I changed line 131 to this:
```
const subject = xs.create<Event>();
```

**Comment by staltz** [comment]
Makes total sense. I'll do that! :+1: Nikhil

**Comment by staltz** [comment]
Try now with v10 rc15. Both issues solved

**Comment by ntilwalli** [comment]
Worked! Thanks!
