### ISSUE TITLE
conversion API for dataflows (and drivers)

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#305]
Wouldn't it be nice if it was easily possible to write app where you can use components created with different stream libraries in mind?

Scenarios where this can be useful include **migrating** to another stream library, or **evaluating** library, or it would just make possible to use **shared components written for `xstream` in `rx` app** and vice versa.

Convention for *driver sources* this could be like for **isolate**: A source would provide two helper methods **`convertSource`** and **`convertSink`** that would take adapter of stream lib which they should to convert **to** (for source) and **from** (for sink).

So basically those function for driver sources would do the same thing as dorivers do with `runSA` (that is passed as second param) while init - convert driver's native streams to some other streams.

Though **the problem is see with non driver sources**, there some conventions would be needed too. But basically such sources are either streams or plain object maps with streams.

API could be taken from @TylorS's https://github.com/TylorS/stream-conversions
Maybe `covertSource` and `convertSink` should take not adapter, but conversion interface from `stream-conversions`

API could look like:
```js
import RxComponent './RxComponent'
import convert from '@cycle/convert'

const XsComponent = convert.rx.to.xstream(RxComponent)

// so XsComponent can be used transparently in xstream app
```

Also `RxComponent` could have like drivers **`streamAdapter`** property that would let *converter* to know from which lib it should convert the dataflow. And API using adapters could look like:

```js
import RxComponent './RxComponent'
import convertToXs from '@cycle/convert/xstream' // converter to xstream
import rxAdapter from '@cycle/rx-adapter'

const XsComponent = convertToXs(RxComponent, rxAdapter)

// if RxComponent.streamAdapter would be defined:
const XsComponent = convertToXs(RxComponent)
```

This is kind of raw idea. What do you think?

**Comment by erkarl** [comment]
I like the idea because it will avoid fragmentation of Cycle's component ecosystem. Not quite sure about the API. What do you think about sort of "auto converting" components that automatically work in your default stream library? Such approach would add a layer of "magic" for the consumer.

**Comment by whitecolor** [comment]
I think (actually sure) auto conversion will not be possible, as inside app we are just dealing with transparent composition of pure functions, and it is non needed, and it should explit thing to avoid ambiguities.

The only option would be using auto proxying like it is done in [cycle-hmr](https://github.com/whitecolor/cycle-hmr) but conversion task is not so ubiquitous and need to run in production, so it is not viable.

**Comment by staltz** [comment]
I think this is a good idea as a community library 👍

**Comment by whitecolor** [comment]
I will make it probably soon.

**Comment by whitecolor** [comment]
made a lib for that https://github.com/whitecolor/cycle-convert

**Comment by staltz** [comment]
Good! Add it to awesome-cyclejs list?

**Comment by whitecolor** [comment]
@staltz What do you think about adding conversion API to existing drivers? This would allow more proper/consistent conversion of driver sources and sinks (for some special cases like **DOM transposition** which is not handled by `cycle-convert` currently). Of course such cases could be quite properly solved without additional API methods in drivers, but it would be more consistent and would not add much code and change to existing drivers internals. 

Just two methods `convertSource` and `convertSinks` along with `isolateSink` and `isolateSource`. (in case of DOM `convertSink` is also needed, in `HTTP` as in most cases needs only `convertSource`)

Just think about it.

**Comment by staltz** [comment]
Conversion between stream libraries has been a big pain in Cycle Diversity, and the only reason why we are doing it is to allow merging of Cycle with Motorcycle, while gradually moving towards xstream as the standard. I don't want to build an all-encompassing stream library agnostic conversion layer, because all of this machinery takes a lot of maintenance and slows us down on other efforts in Cycle as a framework. Meaning that, if we had xstream from day 1, Cycle would be an xstream-only framework.

**Comment by whitecolor** [comment]
@staltz then people would probably port it to other stream libs)

> I don't want to build an all-encompassing stream library agnostic conversion layer, because all of this machinery takes a lot of maintenance and slows us down on other efforts in Cycle as a framework.

I understand you concern. But I can not completely agree with you. You *eventually* discovered very generalized pattern which is not actually suitable only from DOM/HTTP/front-end architectures the same thing, a like thing goes for stream libs. And if you hadn't such libs as rx and most.js as examples xstream may not be born. An they are all very similar and adpater API that you build is really good.

At the end of the day I still think that this stream diversity and ability to use conversion layer adds more value than it takes out. This are very simple things and do not take big maintenance efforts. I would argue that self-made virtual-dom (xs-dom?) is more important endeavor than diversity thing.

People that know (or think they know `rx`) could more easy decide to try `cyclejs` architecture and build app with cycle+rx. And then gradually *convert* it to xstream after they understand it is better in many cases. 

But I understand your approach (having solid pre-defined deafults) for some people/case its more suitable. But for some cases/people it is more valuable to have ability to make later (not painful) decision then having solidly determined options (which they my not be sure in yet).

**Comment by staltz** [comment]
@whitecolor Don't say it is simple and doesn't take big maintenance efforts. I have been updating *-run and *-adapter versions myself and it takes too much of *my* time, even with Tylor's help. We have more important things todo.

**Comment by whitecolor** [comment]
@staltz you could ask me to help for example. And those are kind of tasks that should be solidly accomplished once (good API should be finalized) - some time and decent efforts are required for that - this is obvious. But those libs are really small and simple (and this is the sign of good design decision and correct approach) and will serve as foundation and should not require big efforts in future.

As for adapters API - you already have it this a big part you may consider it to be necessary evil but I consider it as a good part. You still have it and drivers use it (adapters conversions). In this terms conversion API that I was taking about would be just a logical addition to this stuff that already presents de facto.
