### ISSUE TITLE
makeHTMLDriver doesn't support chained select() calls

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/core#306]
the following code works with `makeDOMDriver()` but not with `makeHTMLDriver()`

**Code**
```js
  const searchEl = DOM.select('.search')
  const inputEl = searchEl.select('input')
```
**Error**
```stack
/Users/tushar.mathur/Documents/Projects/musical/src/components/Search.js:71
  var inputEl = searchEl.select('input');
                         ^

TypeError: searchEl.select is not a function
    at exports.default (Search.js:42:28)
    at model (Main.js:21:21)
    at exports.default (Main.js:36:13)
    at Object.run (/Users/tushar.mathur/Documents/Projects/musical/node_modules/@cycle/core/lib/cycle.js:91:15)
    at Object.<anonymous> (/Users/tushar.mathur/Documents/Projects/musical/src/bootstrap-server.js:19:32)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by staltz** [comment]
@tusharmath Which version of Cycle DOM?

**Comment by tusharmath** [comment]
@staltz ` "version": "9.4.0"`

**Comment by TylorS** [comment]
This is already fixed in 10.x, but we should probably get this backported for now.

**Comment by staltz** [comment]
I'd rather try to get v10 out and stable, we need to move forwards more quickly to avoid big gaps in migration.

**Comment by tusharmath** [comment]
@staltz Is `v10` stable? What are the breaking changes?

**Comment by whitecolor** [comment]
@tusharmath you may try) but this should be fixed and released first https://github.com/cyclejs/dom/pull/121

**Comment by rjkip** [comment]
I already fixed this in a fork and was about to submit a pull request when I thought I really should consult with Cycle's issue list first. I'm not sure if you want this fixed on master, but if you're interested, I can submit [this change](https://github.com/cyclejs/dom/compare/master...rjkip:bugfix/html-driver-nested-selects?expand=1) as a PR.

**Comment by staltz** [comment]
Because we're going to release Cycle DOM v10 soon, I'll close this issue.
