### ISSUE TITLE
@cycle/dom 10.0.0-rc17 typing problems

### ISSUE THREAD

**Issue by wmaurer** [cyclejs/core#307]
I've come across a number of problems when building a new cycle / xstream based app using typescript.

1) `Cannot find module '@cycle/dom'`: the typings are not found at all by the typescript compiler.
Solution: add the following line to `@cycle/dom`'s `package.json`: 
```
    "typings": "lib/index.d.ts"
```

2) `makeDOMDriver` returns incorrect type `Function`. It should instead, return `DriverFunction`

3) Too few interfaces are exported from `index.d.ts`. For example, I would like to use the interface `DOMSource`, so that I can define `main` as follows:
```
    interface Sources {
        DOM: DOMSource
    }

    function main(sources: Sources) {...}
```
This way, I would have edit-time intellisense in VSCode (or Atom with atom-typescript)
However, `DOMSource` is not exported from `index.d.ts`.

4) `DOMSource.events()` returns `any`, which means the subsequent `xstream` methods and operators are not type checked. `DOMSource.events()` should have return type `Stream<Event>`

Having this issues fixed for the next RC would be very helpful.

**Comment by wmaurer** [comment]
5) The way that `hyperscript-helpers` has been written, with a list of functions based on an array of strings being created dynamically, doesn't lend itself to automatic creation of typings (see the resulting `hyperscript-helpers.d.ts`.

In this case, I believe that the typings would have to be written by hand, one for each function, e.g.:
```
    export function a(...params: any[]): Object;
    export function abbr(...params: any[]): Object;
    ...
```

6) The `snabdom` custom typings are not landing in the `lib` folder, so:
```
    import { VNode } from 'snabbdom';
```
causes the typescript compiler to complain in `lib/makeHTMLDriver.d.ts`

7) Not specific to `@cycle/dom`: I'm seeing numerous error messages relating to not finding `require`, `Map`, `Promise`, `Array.from`, etc. I'm compiling directly to ES5, using `webpack` and `awesome-typescript-loader`. I'm not sure if this is something specific to my setup ...

Let me know if I can supply more information, or if I can help out.

**Comment by TylorS** [comment]
Thank you for all the reports. They will be investigated :)

**Comment by TylorS** [comment]
Regarding 7 I've generally used `typings install -SA es6-shim`

**Comment by TylorS** [comment]
4. events() has to return any, because it does not specifically return an xstream `Stream` since it does stream conversion, it could just as easily be an Rx Observable. I'd suggest using typecasting there.

**Comment by staltz** [comment]
Thanks wmaurer for the detailed reports. These are priority and we will fix them very soon

**Comment by wmaurer** [comment]
Regarding 4 - events() returning any:
I'm fighting against typescript's external module system to see if it's possible or feasible to have an additional set of typings (xstream specific) which would merge with with the existing `@cycle/dom` typings, thus providing an `events()` function which returns either a `Stream`. This would take advantages of typescript's [open ended interfaces capability](https://basarat.gitbooks.io/typescript/content/docs/types/ambient/interfaces.html). I'll let you know if something comes of this.

Another possibility would be to use typescript's generics, so that `events()` is defined as:
```
    events<T>(eventType: string, options: EventsFnOptions = {}): T<Event>
```  
Usage would be:
```
    sources.DOM.select('.myinput').events<Stream>('input')
        .debug()
```  
which is much nicer than:
```
    (sources.DOM.select('.myinput').events('input') as Stream<Event>)
        .debug()
```

**Comment by staltz** [comment]
Nice suggestions indeed!

**Comment by fenduru** [comment]
Just ran into this. The way I got around the lack of typings was to do:

```ts
import { run } from '@cycle/rxjs-run';
import { makeDOMDriver } from '@cycle/dom/src/index.ts';
import { DriverFunction } from '@cycle/base';
...
run(main, {
  DOM: (makeDOMDriver('body') as DriverFunction)
});
```

**Comment by ntilwalli** [comment]
After being built, none of the individual tag hyperscript-helper functions are being exported in `lib/hyperscript-helpers.d.ts` (checked with 10.0.0-rc21) and I think it's because the d.ts files are being dynamically generated and functions that should be declared are also being dynamically generated and I don't think the compiler is smart enough to iterate on the properties of object exported as `default`. Seems like the tag helpers need to be explicitly listed...

Also those same tag helpers are currently exported from `lib/index.d.ts` but they're not imported in that file, so they point to nothing...

**Comment by wmaurer** [comment]
> Nice suggestions indeed!

Regarding 4) 

Unfortunately, my second suggestion won't work. I now see that Typescript [doesn't yet support ](https://github.com/Microsoft/TypeScript/issues/1213) higher-kinded types.

I think the only way to do this is to supply sets of typings specifically for RxJS or xstream. But this implies that every driver would need a set of typings for each stream library, which is a bit of a pain ...

--

I do have a general suggestion regarding typings. Rather than exporting typings as classes, I would suggest exporting interfaces, which describe the public API of the library.
`DOMSource`, for example, has some internal properties (`_rootElement$`, `_runStreamAdapter`) which can be seen in the public typings.
Instead, I would have `DOMSource` implement an `IDOMSource`**, which only has the public API:
```
export interface IDOMSource {
    select(selector: string): IDOMSource;
    events(eventType: string, options?: EventsFnOptions): any;
}
class DOMSource implements IDOMSource {...}
```

I believe this will help with using [open-ended interfaces](https://basarat.gitbooks.io/typescript/content/docs/types/ambient/interfaces.html) (which I don't think works with classes)

** I intentionally used the `I` prefix here to illustrate the point, but in general, prefixing interfaces with `I` is not recommended in the typescript world. Another naming convention could be better applied.

**Comment by staltz** [comment]
@wmaurer I started solving these issues. Can you help clarify why and how did you perceive this problem?

> 2) makeDOMDriver returns incorrect type Function. It should instead, return DriverFunction

As far as I can see, this shouldn't be perceived. Or is it a problem that Cycle.run should know how to receive any function as a driver?

**Comment by wmaurer** [comment]
@staltz thanks for starting to work on this

`Cycle.run`'s second parameter is `drivers: DriversDefinition`, where `DriversDefinition` is typed as a hash of `DriverFunction`, which looks like:
```
export interface DriverFunction {
    (stream: any, adapter: StreamAdapter, driverName: string): any;
    streamAdapter?: StreamAdapter;
}
```

As a result, the typescript compiler gives me the following error:
![image](https://cloud.githubusercontent.com/assets/2899448/15551458/659e6d64-22b6-11e6-90f3-29afc9fc50cd.png)
(I see the same error when running `tsc` from the console)

If the intention is that `Cycle.run` should receive any function as a parameter, then its second parameter should no longer be a hash of `DriverFunction`, but rather:
```
run(main: (sources: any) => any, drivers: { [driverName: string]: Function }): DisposeFunction;
```

**Comment by staltz** [comment]
Yes, correct, thanks for the feedback, and I think your last paragraph is the right course of action.

**Comment by staltz** [comment]
@TylorS do you have an idea how to solve (6)?

**Comment by TylorS** [comment]
I think we could have a reference tag to custom-typings/main.d.ts in the index.d.ts ?

**Comment by staltz** [comment]
@TylorS Ah yes. That's what's missing.

**Comment by mattiamanzati** [comment]
@staltz Unfortunatelly this does not works, just installed 10.0.0-rc23 but when running tsc 1.8.10 I am getting

```
c:\Shared\XAMPP\htdocs\track>tsc
node_modules/@cycle/dom/lib/index.d.ts(1,1): error TS2654: Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.
node_modules/@cycle/dom/lib/index.d.ts(6,10): error TS2304: Cannot find name 'a'.
node_modules/@cycle/dom/lib/index.d.ts(6,13): error TS2304: Cannot find name 'abbr'.
node_modules/@cycle/dom/lib/index.d.ts(6,19): error TS2304: Cannot find name 'address'.
node_modules/@cycle/dom/lib/index.d.ts(6,28): error TS2304: Cannot find name 'area'.
node_modules/@cycle/dom/lib/index.d.ts(6,34): error TS2304: Cannot find name 'article'.
node_modules/@cycle/dom/lib/index.d.ts(6,43): error TS2304: Cannot find name 'aside'.
node_modules/@cycle/dom/lib/index.d.ts(6,50): error TS2304: Cannot find name 'audio'.
node_modules/@cycle/dom/lib/index.d.ts(6,57): error TS2304: Cannot find name 'b'.
node_modules/@cycle/dom/lib/index.d.ts(6,60): error TS2304: Cannot find name 'base'.
node_modules/@cycle/dom/lib/index.d.ts(6,66): error TS2304: Cannot find name 'bdi'.
node_modules/@cycle/dom/lib/index.d.ts(6,71): error TS2304: Cannot find name 'bdo'.
node_modules/@cycle/dom/lib/index.d.ts(6,76): error TS2304: Cannot find name 'blockquote'.
node_modules/@cycle/dom/lib/index.d.ts(6,88): error TS2304: Cannot find name 'body'.
node_modules/@cycle/dom/lib/index.d.ts(6,94): error TS2304: Cannot find name 'br'.
node_modules/@cycle/dom/lib/index.d.ts(6,98): error TS2304: Cannot find name 'button'.
node_modules/@cycle/dom/lib/index.d.ts(6,106): error TS2304: Cannot find name 'canvas'.
node_modules/@cycle/dom/lib/index.d.ts(6,114): error TS2304: Cannot find name 'caption'.
node_modules/@cycle/dom/lib/index.d.ts(6,123): error TS2304: Cannot find name 'cite'.
node_modules/@cycle/dom/lib/index.d.ts(6,129): error TS2304: Cannot find name 'code'.
node_modules/@cycle/dom/lib/index.d.ts(6,135): error TS2304: Cannot find name 'col'.
node_modules/@cycle/dom/lib/index.d.ts(6,140): error TS2304: Cannot find name 'colgroup'.
node_modules/@cycle/dom/lib/index.d.ts(6,150): error TS2304: Cannot find name 'dd'.
node_modules/@cycle/dom/lib/index.d.ts(6,154): error TS2304: Cannot find name 'del'.
node_modules/@cycle/dom/lib/index.d.ts(6,159): error TS2304: Cannot find name 'dfn'.
node_modules/@cycle/dom/lib/index.d.ts(6,164): error TS2304: Cannot find name 'dir'.
node_modules/@cycle/dom/lib/index.d.ts(6,169): error TS2304: Cannot find name 'div'.
node_modules/@cycle/dom/lib/index.d.ts(6,174): error TS2304: Cannot find name 'dl'.
node_modules/@cycle/dom/lib/index.d.ts(6,178): error TS2304: Cannot find name 'dt'.
node_modules/@cycle/dom/lib/index.d.ts(6,182): error TS2304: Cannot find name 'em'.
node_modules/@cycle/dom/lib/index.d.ts(6,186): error TS2304: Cannot find name 'embed'.
node_modules/@cycle/dom/lib/index.d.ts(6,193): error TS2304: Cannot find name 'fieldset'.
node_modules/@cycle/dom/lib/index.d.ts(6,203): error TS2304: Cannot find name 'figcaption'.
node_modules/@cycle/dom/lib/index.d.ts(6,215): error TS2304: Cannot find name 'figure'.
node_modules/@cycle/dom/lib/index.d.ts(6,223): error TS2304: Cannot find name 'footer'.
node_modules/@cycle/dom/lib/index.d.ts(6,231): error TS2304: Cannot find name 'form'.
node_modules/@cycle/dom/lib/index.d.ts(6,237): error TS2304: Cannot find name 'h1'.
node_modules/@cycle/dom/lib/index.d.ts(6,241): error TS2304: Cannot find name 'h2'.
node_modules/@cycle/dom/lib/index.d.ts(6,245): error TS2304: Cannot find name 'h3'.
node_modules/@cycle/dom/lib/index.d.ts(6,249): error TS2304: Cannot find name 'h4'.
node_modules/@cycle/dom/lib/index.d.ts(6,253): error TS2304: Cannot find name 'h5'.
node_modules/@cycle/dom/lib/index.d.ts(6,257): error TS2304: Cannot find name 'h6'.
node_modules/@cycle/dom/lib/index.d.ts(6,261): error TS2304: Cannot find name 'head'.
node_modules/@cycle/dom/lib/index.d.ts(6,267): error TS2304: Cannot find name 'header'.
node_modules/@cycle/dom/lib/index.d.ts(6,275): error TS2304: Cannot find name 'hgroup'.
node_modules/@cycle/dom/lib/index.d.ts(6,283): error TS2304: Cannot find name 'hr'.
node_modules/@cycle/dom/lib/index.d.ts(6,287): error TS2304: Cannot find name 'html'.
node_modules/@cycle/dom/lib/index.d.ts(6,293): error TS2304: Cannot find name 'i'.
node_modules/@cycle/dom/lib/index.d.ts(6,296): error TS2304: Cannot find name 'iframe'.
node_modules/@cycle/dom/lib/index.d.ts(6,304): error TS2304: Cannot find name 'img'.
node_modules/@cycle/dom/lib/index.d.ts(6,309): error TS2304: Cannot find name 'input'.
node_modules/@cycle/dom/lib/index.d.ts(6,316): error TS2304: Cannot find name 'ins'.
node_modules/@cycle/dom/lib/index.d.ts(6,321): error TS2304: Cannot find name 'kbd'.
node_modules/@cycle/dom/lib/index.d.ts(6,326): error TS2304: Cannot find name 'keygen'.
node_modules/@cycle/dom/lib/index.d.ts(6,334): error TS2304: Cannot find name 'label'.
node_modules/@cycle/dom/lib/index.d.ts(6,341): error TS2304: Cannot find name 'legend'.
node_modules/@cycle/dom/lib/index.d.ts(6,349): error TS2304: Cannot find name 'li'.
node_modules/@cycle/dom/lib/index.d.ts(6,353): error TS2304: Cannot find name 'link'.
node_modules/@cycle/dom/lib/index.d.ts(6,359): error TS2304: Cannot find name 'main'.
node_modules/@cycle/dom/lib/index.d.ts(6,365): error TS2304: Cannot find name 'map'.
node_modules/@cycle/dom/lib/index.d.ts(6,370): error TS2304: Cannot find name 'mark'.
node_modules/@cycle/dom/lib/index.d.ts(6,376): error TS2304: Cannot find name 'menu'.
node_modules/@cycle/dom/lib/index.d.ts(6,382): error TS2304: Cannot find name 'meta'.
node_modules/@cycle/dom/lib/index.d.ts(6,388): error TS2304: Cannot find name 'nav'.
node_modules/@cycle/dom/lib/index.d.ts(6,393): error TS2304: Cannot find name 'noscript'.
node_modules/@cycle/dom/lib/index.d.ts(6,403): error TS2304: Cannot find name 'object'.
node_modules/@cycle/dom/lib/index.d.ts(6,411): error TS2304: Cannot find name 'ol'.
node_modules/@cycle/dom/lib/index.d.ts(6,415): error TS2304: Cannot find name 'optgroup'.
node_modules/@cycle/dom/lib/index.d.ts(6,425): error TS2304: Cannot find name 'option'.
node_modules/@cycle/dom/lib/index.d.ts(6,433): error TS2304: Cannot find name 'p'.
node_modules/@cycle/dom/lib/index.d.ts(6,436): error TS2304: Cannot find name 'param'.
node_modules/@cycle/dom/lib/index.d.ts(6,443): error TS2304: Cannot find name 'pre'.
node_modules/@cycle/dom/lib/index.d.ts(6,448): error TS2304: Cannot find name 'q'.
node_modules/@cycle/dom/lib/index.d.ts(6,451): error TS2304: Cannot find name 'rp'.
node_modules/@cycle/dom/lib/index.d.ts(6,455): error TS2304: Cannot find name 'rt'.
node_modules/@cycle/dom/lib/index.d.ts(6,459): error TS2304: Cannot find name 'ruby'.
node_modules/@cycle/dom/lib/index.d.ts(6,465): error TS2304: Cannot find name 's'.
node_modules/@cycle/dom/lib/index.d.ts(6,468): error TS2304: Cannot find name 'samp'.
node_modules/@cycle/dom/lib/index.d.ts(6,474): error TS2304: Cannot find name 'script'.
node_modules/@cycle/dom/lib/index.d.ts(6,482): error TS2304: Cannot find name 'section'.
node_modules/@cycle/dom/lib/index.d.ts(6,491): error TS2304: Cannot find name 'select'.
node_modules/@cycle/dom/lib/index.d.ts(6,499): error TS2304: Cannot find name 'small'.
node_modules/@cycle/dom/lib/index.d.ts(6,506): error TS2304: Cannot find name 'source'.
node_modules/@cycle/dom/lib/index.d.ts(6,514): error TS2304: Cannot find name 'span'.
node_modules/@cycle/dom/lib/index.d.ts(6,520): error TS2304: Cannot find name 'strong'.
node_modules/@cycle/dom/lib/index.d.ts(6,528): error TS2304: Cannot find name 'style'.
node_modules/@cycle/dom/lib/index.d.ts(6,535): error TS2304: Cannot find name 'sub'.
node_modules/@cycle/dom/lib/index.d.ts(6,540): error TS2304: Cannot find name 'sup'.
node_modules/@cycle/dom/lib/index.d.ts(6,545): error TS2304: Cannot find name 'svg'.
node_modules/@cycle/dom/lib/index.d.ts(6,550): error TS2304: Cannot find name 'table'.
node_modules/@cycle/dom/lib/index.d.ts(6,557): error TS2304: Cannot find name 'tbody'.
node_modules/@cycle/dom/lib/index.d.ts(6,564): error TS2304: Cannot find name 'td'.
node_modules/@cycle/dom/lib/index.d.ts(6,568): error TS2304: Cannot find name 'textarea'.
node_modules/@cycle/dom/lib/index.d.ts(6,578): error TS2304: Cannot find name 'tfoot'.
node_modules/@cycle/dom/lib/index.d.ts(6,585): error TS2304: Cannot find name 'th'.
node_modules/@cycle/dom/lib/index.d.ts(6,589): error TS2304: Cannot find name 'thead'.
node_modules/@cycle/dom/lib/index.d.ts(6,596): error TS2304: Cannot find name 'title'.
node_modules/@cycle/dom/lib/index.d.ts(6,603): error TS2304: Cannot find name 'tr'.
node_modules/@cycle/dom/lib/index.d.ts(6,607): error TS2304: Cannot find name 'u'.
node_modules/@cycle/dom/lib/index.d.ts(6,610): error TS2304: Cannot find name 'ul'.
node_modules/@cycle/dom/lib/index.d.ts(6,614): error TS2304: Cannot find name 'video'.
node_modules/@cycle/dom/lib/isolateModule.d.ts(16,17): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
node_modules/@cycle/dom/lib/isolateModule.d.ts(19,18): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

c:\Shared\XAMPP\htdocs\track>
```

**Comment by staltz** [comment]
I'm working on it...

**Comment by staltz** [comment]
@wmaurer @fenduru @ntilwalli @mattiamanzati can you try and see if DOM 10.0.0-rc26 fixes your issues? All issues except number (4) should be fixed, and I put out an example using TypeScript: https://github.com/cyclejs/examples/tree/diversity/bmi-typescript

**Comment by mattiamanzati** [comment]
@staltz Yep! I confirm that with tsc or ts-loader fixes all the problems!

**Comment by staltz** [comment]
Ok, good news! I'll close this issue, but we can still comment here, of course. If we have more TS issues, we can open other issues.

**Comment by wmaurer** [comment]
Hi @staltz, sorry for not replying earlier - been busy with family and work ...
Thanks for your work on this. It certainly has removed all the compile-time errors I was experiencing.

Do you have any ideas for fixing (4)? I could imagine having a some xstream specific typings for cycle/dom. I placed the following in my app's `custom-typings` folder, which solved my immediate problem:
```
import { IDOMSource, EventsFnOptions } from '@cycle/dom';
import { Stream } from 'xstream';

declare module '@cycle/dom' {
    export class DOMSource {
        select(selector: string): DOMSource;
        events(eventType: string, options?: EventsFnOptions): Stream<Event>;
    }
}
``` 
(... though to do this I really need `EventsFnOptions` to be exported by cycle/dom)

Should I open a new issue to continue discussing the possibilities to solve (4)?

**Comment by staltz** [comment]
Yes, lets open a new issue for that, and I have some ideas for solving it.

**Comment by wmaurer** [comment]
Ok, I'll kick it off ...
