### ISSUE TITLE
scroll event does not bubble

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/core#308]
I am note sure if I already created this issue some time ago. I am not able to find it so I create it now.

The `scroll` event does not bubble (https://developer.mozilla.org/en-US/docs/Web/Events/scroll) but is not in the list of non-bubbling events (https://github.com/cyclejs/dom/blob/master/src/render-dom.js#L109).

So `DOM.select('.foo').events('scroll')` is not working.

**Comment by mickylad** [comment]
Simple workaround for this currently is `DOM.select('.foo').events('scroll', { useCapture: true });`

**Comment by staltz** [comment]
Fixed in Cycle DOM 10.0.3
