### ISSUE TITLE
[cycle-dom] transposition not working as expected

### ISSUE THREAD

**Issue by jacekkolasa** [cyclejs/core#309]
When using stream transposition in vtree, along with {textContent: '...'}, the last child in array is not re-rendering.

[https://jsbin.com/cucecoyome/1/edit?js,console,output](https://jsbin.com/cucecoyome/1/edit?js,console,output)

```
function main(sources) {
  const interval$ = Observable.interval(1000)
    .timeInterval()
    .take(10)
    .map(({value}) => div('value ' + value))
    .share();
  
  
  return {
    DOM: Observable.of(1)
      .map(() => {
        return div(
          // commenting out the next line make the intervals$
          // showing properly
          {textContent: 'text'},
          [
            interval$,
            interval$,
            interval$
          ]
        );
      })
  }
}
```

the result:
```
text
value 9
value 9
value 0
```
expected result (it's working like this when {textContent...} is commented out) :
```
text
value 9
value 9
value 9
```

**Comment by whitecolor** [comment]
Why do you want to set content using `{textContent: 'text'}` and then fill it with children?

**Comment by jacekkolasa** [comment]
That is probably a wrong use of vDom, so this bug could be very low priority. Anyway, it's interesting that only the last stream is not updating. That could be confusing for some beginners (it's hard to find the detailed documentation of cycle-dom).

**Comment by staltz** [comment]
Seems to work fine with xstream v4, `@cycle/xstream-run` and `@cycle/dom` v10.0.0-rc28 
http://www.webpackbin.com/N1rvi2A7W
