### ISSUE TITLE
DOM API to be made more message based

### ISSUE THREAD

**Issue by SteveALee** [cyclejs/core#315]
One way to look at cycle is as messages flowing in from source drivers and out to sink drivers via pure synchronous (usually) code.

This is really powerful (even classical OOP should have focused on Messages, according to Alan Kay)

Drivers can actually accept (and possibly emit) 2 types of message; Data and Commands

For example the [history driver](https://github.com/cyclejs/history) accepts paths ```'/'``` or commands ```{type: go, value: -1}```

(This appears to be similar to OS drivers [ioctl](https://en.wikipedia.org/wiki/Ioctl) mechanism)

This results in a flow in the main that is consistent for data and commands. The code sends an output message and later gets async messages in which are dealt with as they occur. Usually with out much need for state to be kept between the 2 effectively independent actions. This is a well establish pattern for async message based systems. It can make tracing transactions a bit harder but logging incoming and outgoing messages helps 

# DOM
so the point of this issue is (at last) the DOM driver doesn't work this way. the Source is not a stream like other drivers. Rather it is an object that has fluid style operators that you use to make select the stream you want. eg

```const intentUsername$ = DOM.select('.username').events('change')```

Why not change this so it receives commands like so

```{select: '.username', event: 'change'}```

**Comment by SteveALee** [comment]
A side effect is that all sources can use $ if you so like.

**Comment by laszlokorte** [comment]
Then how would I get the stream of `change` events?

At a first glance for me that looks like a step backwards because you move from a declarative way of working with events back to an imperative way. Would there be commands for removing listeners as well?

**Comment by SteveALee** [comment]
> Then how would I get the stream of change events?

From DOM$ in your sources not from 
```const intentUsername$ = DOM.select('.username').events('change')```

> At a first glance for me that looks like a step backwards because you move from a declarative way of working with events back to an imperative way. 

Maybe depends on your definition of 'imperative'. To my mind message are declarative You raise a point though, you create the messages on demands, not statically when the main function is executed. Arguably you should only get events in certain circumstances decided by the logic. Currently you have to ignore messages should you not wanted them anymore, or remove the DOM node. Neither of which appear less explicit.

> Would there be commands for removing listeners as well?

I should think so. Can we remove the listeners in the current setup?

> What about the following: A drag event. I want to listen for mousemove events that happen between the mousedown and the corresponding mouseup event. Would I need send a {... event: 'mousedown'} message to the driver first, then await the result, then send a {... event: 'mousemove'} message?

I don't think there would be any specific response for setting a handler. Perhaps a failure, which is like the current situation, though the impact of failure is different. You'd just start getting the events. So in your example you send the 2 commands and the events come in. Perhaps a message format to support aggregated commands could exists.

This does highlight a key difference though. Currently you use a selector to get each stream, 1 for each selector/event pair. This alternative would mean everything comes in via DOM$ and you'd have to filter to get separate streams. 

Another difference is timing. As it is the streams are set up one at a time at the point the main runs. If you send commands the timing is quite different, as each command is processed. May be more complex to handle - may not.

> I am not seeing the point at all. But maybe I am missing something entirely.

Just the idea of a consistent messaged based model. I wanted see if it has legs. Perhaps not :)

> btw: The dom driver is not the only driver that provides objects with methods instead of raw observables.

Ah - which would those be. I've obviously not used them yet.

**Comment by laszlokorte** [comment]
> Another difference is timing. As it is the streams are set up one at a time at the point the main runs. 

Yeah that's kind of the disadvantage from my perspective. Currently with Rx I do not have to care about when exactly the listeners get added (they get attached to the dom when the stream is subscribed and are detached if no longer needed - but that's an implementation detail).

A simple drag-n-drop handling can be build like this:

```
O.fromEvent('.draggable', 'mousedown').flatMapLatest(() =>
  O.fromEvent(document, 'mousemove').takeUntil(O.fromEvent(document, 'mouseup'))
).map((evt) => ...)
```

It's a declarative way of working with the events, similar to an SQL query it says: "give me the mouse move events between a mousedown and a mouseup events". But just these 3 lines do not even attach the listeners to the dom. I may happen on subscription and I do not have to care.

Now please show me how I would do that with the API you propose. I would have to send messages to the dom driver *in the correct order* to tell it to "now please add a listener for the mousedown event", "now please add a mousemove listener", "now please remove the listener you just added". Yeah each message might be an object that can be constructed declaratively but the combination of messages is an imperative sequence. 

> Ah - which would those be. I've obviously not used them yet.

New version of the http driver has a `select` method. localstorage driver as a `get` method for accessing values streams by key.

**Comment by SteveALee** [comment]
That's a great example. I was trying to think of why the Rx fluid style could be useful for the DOM. The ```fromEvent``` wrapper made it much clearer.  We wrap "almost streams" with the Obs lib creators. Doesn't Rx have a from Event too?  Is good enough for me. I won't close just yet though in case other's have thoughts. Glad I asked as I learnt something :)

So perhaps the fluid model is the one to make more drivers use, when it make sense. I'll look at mine.

> New version of the http driver has a select method. localstorage driver as a get method for accessing values streams by key.

Can you point to that local strorage driver. The on I was using accept the key in the factory function.

**Comment by laszlokorte** [comment]
> The fromEvent wrapper made it much clearer. We wrap "almost streams" with the Obs lib creators. Doesn't Rx have a from Event too?

I am not sure I understand what you are saying. The main reason you can not just use the Rx fromEvent constructor directly but have to use `DOM.select(...).events(...)` is that the element's you are referring to are created at runtime and may even change at runtime. So the DOM driver has to do some additional book keeping in order to provide you with the correct event streams.

> Can you point to that local strorage driver. The on I was using accept the key in the factory function.

https://github.com/cyclejs/storage/blob/master/example/app.js#L21-L23

**Comment by SteveALee** [comment]
I've no idea how I missed that driver. Is making my head spin a bit. 

Thanks for the education!
