### ISSUE TITLE
nested isolation breaks in dom diversity branch

### ISSUE THREAD

**Issue by jemmyw** [cyclejs/core#316]
When you isolate a component A that uses another isolated component B, and A does not have it's own vTree, A will overwrite the isolation of B's root vNode.

This example will surface the issue. The first page of the B component will work fine and the button will show page 2. Page 2 will display but the button won't work.

The reason is that A will isolate the first vNode (loading) to cycle1. B will isolate it's first vNode (page 1) to cycle2. A will then overwrite B's vnode isolation with cycle1. Then the loading vNode is removed and the remove function in isolateModule.ts will delete isolation cycle1.

```javascript
const B = sources => {
  const showIntent$ = Observable.merge(
    sources.DOM.select('.show-1').events('click').map(1),
    sources.DOM.select('.show-2').events('click').map(2)
  ).startWith(1)

  const pages = [
    div('.b', [
      button('.show-2', 'Show page 2')
    ]),
    div('.b', [
      button('.show-1', 'Show page 1')
    ])
  ]

  return {
    DOM: showIntent$.map(page => pages[page])
  }
}

const A = sources => {
  const loading = div('.loading', ['Loading...'])
  const b = isolate(B)(sources)

  return {
    DOM: b.DOM.startWith(loading)
  }
}

const main = sources => {
  const a = isolate(A)(sources)

  return {
    DOM: a.DOM
  }
}
```

**Comment by staltz** [comment]
Thanks. I'll merge your PR too. I'll close this issue when it has a test too.

**Comment by TylorS** [comment]
@staltz I have tests for this in my PR for the same issue.

**Comment by staltz** [comment]
Oh, good.

**Comment by staltz** [comment]
v10.0.0-rc22 released with a fix. We can reopen this issue if it persists somehow.
