### ISSUE TITLE
@cycle/base does not come compiled

### ISSUE THREAD

**Issue by leiserfg** [cyclejs/core#317]
How do i need to install babelify for it if i am programing in coffeescript
Error: Cannot find module 'babelify' from '/home/leiserfg/Src/cycle-diversity/node_modules/@cycle/base

**Comment by whitecolor** [comment]
You probably doing something wrong, you may describe your setup

**Comment by leiserfg** [comment]
That is my 
"dependencies": {
    "@cycle/xstream-run": "*",
    "xstream": "*",
    "@cycle/dom": "10.0.0-rc22",
    "@cycle/http": "9.0.0-rc3"

  }

**Comment by whitecolor** [comment]
loading/bundling setup, etc, try with webpackbin.com

**Comment by leiserfg** [comment]
It's my full package
{
  "name": "cycle-bp-coffee",
  "version": "1.0.0",
  "description": "",
  "repository": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "beefy src/main.coffee:dist/main.js --live -- -t coffeeify --extension='.coffee'",
    "build": "browserify src/main.coffee -t coffeeify --extension='.coffee' | uglifyjs -c dead_code,unused -m > dist/main.js",
    "debug": "browserify --debug src/main.coffee -t coffeeify --extension='.coffee' > dist/main.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@cycle/xstream-run": "*",
    "xstream": "*",
    "@cycle/dom": "10.0.0-rc22",
    "@cycle/http": "9.0.0-rc3"

  },
  "devDependencies": {
    "coffeeify":"^2.0.1",
    "beefy": "^2.1.5",
    "browserify": "^11.2.0",
    "uglify-js": "^2.6.2"
  }
}

**Comment by whitecolor** [comment]
see what files are required from @cycle/base 
it should be taken from `@cycle/base/lib/index.js` - it is compiled source.

And use markdown styling for posted code/configs.

**Comment by TylorS** [comment]
@leiserfg I've worked with coffeescript no problem before: http://www.webpackbin.com/EkyPi54GW

**Comment by leiserfg** [comment]
Sorry for the unestilised config :D and thanks for your help, I'am no using @cycle/base directly it's my full code 
```coffee
{run} = require '@cycle/xstream-run';
{div, button, br, input, p,  makeDOMDriver} = require '@cycle/dom'

main = ({DOM}) ->
  inc$ = DOM.select('.add').events('click').map -> +1
  dec$ = DOM.select('.dec').events('click').map -> -1

  modify = inc$.merge(dec$).startWith 0
  domsink = modify
    .scan (a, b) -> a + b
    .map (val) ->
      div [
        button '.add', '+'
        button '.dec', '-'
        p String val
      ]
  {DOM: domsink}

run main, {
  DOM: makeDOMDriver '#app'
}

```

**Comment by staltz** [comment]
Can you replace
```
    "@cycle/xstream-run": "*",
    "xstream": "*",
```
with
```
    "@cycle/xstream-run": "1.1.0",
    "xstream": "2.6.1",
```
Then remove the node_modules folder and run `npm i` again?

**Comment by leiserfg** [comment]
I made it work by adding:
```js
"babel-preset-es2015":"*",
"babelify": "*"
```
to the devDependencies.
I think it's a problem because I'am programing in coffeescript not with es6.
