### ISSUE TITLE
@cycle/dom@9.x.x: Double click events when clicking a button (get random user example)

### ISSUE THREAD

**Issue by pvelin** [cyclejs/core#319]
I tried the HTTP example (get random user) in the Basic Examples section and I get two users after clicking the button. I noticed that there is two click events for every button click. Same problem with all the versions above @8.0.0
Here are my dependecies for the tutorial
"dependencies": {
    "@cycle/core": "^6.0.3",
    "@cycle/dom": "^9.4.0",
    "@cycle/http": "^8.2.2",
    "rx": "^4.1.0",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1"
  }

**Comment by laszlokorte** [comment]
How do you see that two click events happen?

**Comment by pvelin** [comment]
I added do(x => console.log(x)) after the click stream

**Comment by pvelin** [comment]
and after the randomNum calculation I added console.log and it gets hit twice

**Comment by laszlokorte** [comment]
Strange, I am getting only one `console.log`. Did you change anything else? We are talking about this, right?

**Comment by pvelin** [comment]
I just copied the example from http://cycle.js.org/basic-examples.html and ran it. If I change to @cycle/dom@8.0.0 it works fine. That version is used in jsbin box

**Comment by laszlokorte** [comment]
Hm, that's exactly the same code. Could you create a repo reproducing the issue?

**Comment by pvelin** [comment]
I am total newbie on this so could you please explain what do you mean by repo reproducing the issue?

**Comment by laszlokorte** [comment]
Oh sorry,

I assume you created a new project locally on your machine (a folder containing the package.json definining your dependencies and your javascript and html files). Or are you trying cyclejs just online via jsbin.com or webpackbin.com?

It would be helpful if I could take a quick look at your whole project to have all the context available. It's hard to track down the issue without seeing your whole setup.
So it would be great if you could upload your whole folder - for example by creating a git repository (repo) and upload it to github.

In case you just working in jsbin or webpackbin or some other online code editor it would be fine if you post the link.

**Comment by pvelin** [comment]
Yes I created a new project locally. I will upload it and let you know when it is available

**Comment by pvelin** [comment]
And I found the solution. I was using this webpack.config.js https://github.com/Mercateo/component-check#introducing-webpack. Somehow I managed to create two index.html files one under dist and one under src. I removed the one under src and all the html-webpack-plugin related stuff and now it is working. I am very sorry about the hassle and thank you for the help

**Comment by laszlokorte** [comment]
Interesting...

Did you see two "Get random user" buttons as well?

**Comment by pvelin** [comment]
Actually yes couple of times after changing something :-)

**Comment by laszlokorte** [comment]
Ok, than the problem was simply that your javascript file got included into the html file twice. (probably because your wrote ´<script src="..."></script>` into your html file and then webpack did insert another script tag on it's own.

So everything happened twice: two buttons, two click events, two requests...

**Comment by pvelin** [comment]
Great. Thank you again. This was a good learning experience
