### ISSUE TITLE
hyperscript `createTagFunction` changes number zero to `{}`

### ISSUE THREAD

**Issue by bloodyKnuckles** [cyclejs/core#320]
The hyperscript `createTagFunction` changes number zero to `{}`, which results in the output HTML not displaying the zero.

`span('#count', 0)`

...results in:

`<span id="count"></span>`

The above `span` function is created by the `createTagFunction` function. In the `hyperscript` function returned by `createTagFunction`, the second argument, `0`, gets passed through to the returned `hyperscript` function but is equated to `false` by `!!b` in two conditional statements and as a result gets swapped with an empty object on line 417.

```
function createTagFunction(tagName) {
    return function hyperscript(first, b, c) {
        if (isSelector(first)) {
            if (!!b && !!c) {
                return hyperscript_1.default(tagName + first, b, c);
            } else if (!!b) {
                return hyperscript_1.default(tagName + first, b);
            } else {
                return hyperscript_1.default(tagName + first, {});     //<-- line 417
            }
        } else if (!!b) {
            return hyperscript_1.default(tagName, first, b);
        } else if (!!first) {
            return hyperscript_1.default(tagName, first);
        } else {
            return hyperscript_1.default(tagName, {});
        }
    };
}

```
https://github.com/cyclejs/dom/blob/master/src/hyperscript-helpers.ts#L15-L21

Of course this can be avoided in the end-user code with either:

```
span('#count', '0')
span('#count', `${count}`)
span('#count', count || '0')

```

`!!` (truthy) is the check used here and that reads the number zero as `false`. 

Is there an alternative check that can be used here that will pass number zero as `0`?

**Comment by thysultan** [comment]
``b !== void 0 && b !== null && b !== false``
you can also avoid it end-user code with ``span('#count', x + '')`` x being a value that can be 0

**Comment by staltz** [comment]
Thanks for reporting.

Note to however would implement a fix for this: we can try replacing `!!b` checks with `typeof b !== 'undefined'` first. Let's hope snabbdom knows how to coerce numbers to strings. If it doesn't, we can do that in our hyperscript.

**Comment by bloodyKnuckles** [comment]
I changed `!!b` to `typeof b !== 'undefined'` in my v7.0.0 *cycle-examples/hello-world* and now:

`span('#count', 0)`

...successfully results in:

`<span id="count">0</span>`

Does that show Snabbdom knows how to coerce numbers to string? If so I'm glad to make the pull request.

[Here](https://github.com/cyclejs/dom/blob/master/src/hyperscript-helpers.ts#L15-L21) change:
```
if (!!b && !!c) {
  return h(tagName + first, b, c);
} else if (!!b) {
  return h(tagName + first, b);
} else {
  return h(tagName + first, {});
}
```
...to:
```
if (typeof b !== 'undefined' && typeof c !== 'undefined') {
  return h(tagName + first, b, c);
} else if (typeof b !== 'undefined') {
  return h(tagName + first, b);
} else {
  return h(tagName + first, {});
}
```

Am I missing something?

**Comment by staltz** [comment]
Done in Cycle DOM v10.0.6
