### ISSUE TITLE
cycle/dom stream library specific typings

### ISSUE THREAD

**Issue by wmaurer** [cyclejs/core#322]
As discussed in point (4) of #307 regarding Typescript typings, `@cycle/dom`'s (RC) `DOMSource.events()` returns `any`. This is done intentionally, as cycle's future is to be stream library agnostic, i.e. it should be able to be used with `xstream`, `RxJS`, `most`, etc.

However from an application developer's point of view, `DOMSource.events()` would ideally return the type appropriate to the stream library (in `xstream`'s case `Stream<Event>`), as this will help with compile time and edit time error checking and intellisense.

This issue is not specific to `@cycle/dom`. Any cyclejs driver which is stream library agnostic would have a similar problem. Solving this issue for `@cycle/dom` would set a common approach for all cyclejs drivers.

On approach would be to create a set of typings specific to each stream library. For example, for `@cycle/dom`, I have a simplified set of typings in my application's custom-typings directory:
```
import { IDOMSource, EventsFnOptions } from '@cycle/dom';
import { Stream } from 'xstream';

declare module '@cycle/dom' {
    export class DOMSource {
        select(selector: string): DOMSource;
        events(eventType: string, options?: EventsFnOptions): Stream<Event>;
    }
}
```

This issue is to discuss the best and most convenient options for solving this typings issue for cyclejs drivers.

**Comment by TylorS** [comment]
@wmaurer You should be able to just use type casting, no?

```typescript
import {Stream} from 'xstream'
...
const click$: Stream<Event> = <Stream<Event>> sources.DOM.select('.foo').events('click')
```

**Comment by wmaurer** [comment]
Of course ;-)
But the point is that becomes rather tiresome when one has to do it repetitively. My goal is to not have such untyped return values. Correct typings help with intellisense, code navigation and API exploration. I rarely have to use casts if the typings are good.

I have a solution that works for me. I'd like to see other Typescript / cyclejs profit from it or ideally from a better solution.

**Comment by staltz** [comment]
We can't seem to find how to automagically make `DOMSource` know which stream library type it is returning via `events()`. That would be the ideal case, but he are hitting the limits of TypeScript. So which of these two options seems the least worst?

(1) DOMSource is a generic and you need to tell what are the types it returns when calling `events()` and `elements`: `DOMSource<Stream<Event>, Stream<Element>>`. This would need to be typed anywhere we have a function that expects a DOMSource.

(2) A custom typings file similar to what you made, but it would have to be imported **separately** and included via `typings` for instance. After that, everything works automagically.

**Comment by Frikki** [comment]
Would option 1 allow for type conversions but option 2 not?

**Comment by staltz** [comment]
What exactly do you mean by type conversions?

**Comment by wmaurer** [comment]
My initial reaction was (1) in order to avoid the cycle community having to maintain many typings files.
However the more I think about it, the more I think (1) could end up being a nightmare.

The fact is that this is not a `@cycle/dom` specific problem. It will be a problem for Typescript users for all cyclejs drivers. Imagine we had a driver which makes an `XYZSource` available, which has many methods returning many different stream types. Then it would be `XYZSource<<Stream<A>, Stream<B>, Stream<C>, ... etc >`. Having to repeat this throughout the application would be very tiresome.

Therefore I think that (2) is the least worst option.

**Comment by Frikki** [comment]
Erhm, I think I misread your proposal. Let me try to re-formulate. Option 1 lets us directly specify the return types, whereas option 2 doesn’t (except from a typings file). Thus, option 1 would, in theory, allow for different `DOMSource` return types across an app (though that may possibly never be needed in an app).

**Comment by staltz** [comment]
@Frikki you can always cast, as an escape hatch, but casting is too verbose in a large project. 

@wmaurer I'm starting to agree with you here that (2) is the least worst. The API for Cycle DOM's DOMSource shouldn't actually change much anymore.

**Comment by donaldpipowitch** [comment]
Currently I'd favor (1) any time as I don't like to manage additional typings with `tsd` or `typings` or other tools. However this may change in TypeScript 2.0. You'll probably manage additional typings with npm and TypeScript alone (see [this comment](https://github.com/Microsoft/TypeScript/issues/8889#issuecomment-224336498)). Maybe we should wait for TS 2.0 to make a decision?

**Comment by wmaurer** [comment]
@donaldpipowitch I'm not sure how I understand how Typescript 2.0's method of managing typings will solve this problem.

As I see it Typescript 2.0's method of managing typings will simply change where typings are hosted (npm), instead of via typings/github.
The core problem of `@cycle/dom` being stream-library independent, and thus needing additional typings does not change. With Typescript 2.0, the additional typings will simply be differently managed.

**Comment by staltz** [comment]
Funny that most votes went for (1), because I started feeling like (2) will be nicer. Curious if anyone has **strong** opinions for (1)? Using `typings` is IMHO quite easy, specially if we have good docs around that, e.g. "if you want xstream-specific type defs for Cycle DOM, do this and that". Not importing those typings is still an option, then people need to cast.

**Comment by staltz** [comment]
I found a third option, and quite a decent one:

(3) DOMSource will be anyway an interface. We can separately import the type defs for DOMSource + stream library, for instance:

```js
import {div, span, makeDOMDriver} from '@cycle/dom';
import {DOMSource} from '@cycle/dom/xstream-typings';
```

No need for managing/installing the typings, and no verbose generic interface. How does that sound?

**Comment by donaldpipowitch** [comment]
> @donaldpipowitch I'm not sure how I understand how Typescript 2.0's method of managing typings will solve this problem.

For me it is a nicer DX and DX is important for me. I personally don't want (2) because of the way `tsd` and `typings` work (IMHO they are _not_ so easy to use 😄).

(3) is okay.

Another opinion for (1): I guess it is more idiomatic? `DOMSource<Stream<Event>, Stream<Element>>` is very similar how we handle things like `Promise<Foo>` in TypeScript, right?

**Comment by ShayMatasaro** [comment]
I dont use Typescript at all,  so take  my 2c with a grain of salt :)

While typing is nice, by now i have gotten used to plain JS with ES6, and a lot of typing of type checks can also be done in JS without the need for another transpailer.

Having TrueType as in integral part of a lib ,might reduce the number of potential contributors , when compared to ES 6

**Comment by donaldpipowitch** [comment]
> Having TrueType as in integral part of a lib ,might reduce the number of potential contributors , when compared to ES 6

TrueType? You mean TypeScript, right? Cycle already uses TypeScript internally so it isn't a question about _"Should Cycle use TypeScript internally or not"_ in this issue.

"plain JS with ES6" is nice. I guess you use Babel? Well, TypeScript is basically "plain JS with ES6 and types". It can be learned in some hours (if not minutes). If you willing to use the build step necessary for Babel it is basically the same investment for TypeScript. You should try it once :)

**Comment by wmaurer** [comment]
@staltz thanks, I think (3) is very sensible and will work in this case

There is the possibility that it could cause problems in other cases, i.e. if a function (`fn`) you import from `@cycle/dom` were to return a `DOMSource`, then in the client app, Typescript will not use the `DOMSource` from `xstream-typings`, it will use the `DOMSource` from `@cycle/dom`. This would be solved by also redefining `fn` in `xstream-typings` and importing from there. This could be a source of confusion for users if they import `fn` from the wrong place, but that can be solved by good guidance and documentation.

As far as DX is concerned, I think this option (3) is the best, as `typings` is the pretty much standard way of managing definitions right now, and if Typescript 2.0 provides another mechanism, then the `xstream-typings` approach is still valid, the source of the type definitions simply changes.

**Comment by staltz** [comment]
Yeah, spot on. The only case for `fn` so far is `mockDOMSource`. `makeDOMDriver` and `makeHTMLDriver` are not affected because the drivers are called internally in Cycle.run, so writing `main(sources: {DOM: DOMSource})` simply means "the main expects this".

**Comment by staltz** [comment]
I believe this issue is now solved with 
```js
    "@cycle/dom": "10.0.0-rc30",
    "@cycle/http": "9.0.0-rc8",
```

Check out these examples:

**Comment by wmaurer** [comment]
Thanks @staltz, this works well for me.

BTW, if anybody is using webpack, for some reason at the time of writing, `awesome-typescript-loader` doesn't seem to want to find `@cycle/dom/xstream-typings`, but `ts-loader` does. I'm unable to track down the reason right now, but this info might save you some time.

**Comment by staltz** [comment]
@wmaurer You could try putting .d.ts after xstream-typings
