### ISSUE TITLE
Diversity click stream

### ISSUE THREAD

**Issue by ShayMatasaro** [cyclejs/core#325]
I am  using diversity and :  
const click$ = DOM.select(id).events('click')
doesn't work 
only when i add  .startWith it starts working properly 
maybe another issue related to streams that were previously a memoryStream

  "@cycle/dom": "^10.0.0-rc28",
    "@cycle/history": "^3.1.1",
    "@cycle/xstream-run": "^2.0.0",
    "xstream": "^4.0.1"

http://www.webpackbin.com/4yARb3yEb

**Comment by ntilwalli** [comment]
This is not a bug.  It is standard that all sink-source "cycle"s must be kicked off manually.  If you read the docs (midway down this page http://cycle.js.org/basic-examples.html) you'll see this explicitly discussed.  It's a chicken-egg problem without explicit `startWith`.  The events stream is based on a DOM that hasn't been constructed yet and the DOM is based on clicking on an event's stream that hasn't been attached to any element yet.

**Comment by Hypnosphi** [comment]
What exactly this example should render? A button which appears after being clicked?

**Comment by ShayMatasaro** [comment]
the clicks$  isnt being used to render the vtree$,  the dom is always static :   
button(id,'test')
so it does not need to have an initial value , 

i believe that the combine function should run properly , even when clicks$ has no default value,

but its possible that this is a corner use case .....

**Comment by ntilwalli** [comment]
The `click$` is being used to render the `vtree$` in your posted example.  If that's not what you intended and you intend for the `vtree$` to output a static dom then you should change the `DOM` sink to be `xs.of(button(id, 'test'))`.  As it currently stands the DOM sink is based on a `combine` of the `click$` with nothing else which is effectively the same as just writing `click$.mapTo(button(id, 'test'))`.  `combine` is not like `fold`.  It does not have an implicit `startWith`-like emission, it simply combines the output of the input streams and it only ever outputs after all the input streams emit at least once.  In this case there is only one input stream and it never emits so `combine` never emits...

**Comment by ShayMatasaro** [comment]
thanks, 
i see your point , ill close the issue
