### ISSUE TITLE
Testing DOM in CycleJS

### ISSUE THREAD

**Issue by sarneeh** [cyclejs/core#327]
I've just tried to do some CycleJS in a small app and I've failed at the start already. The library/architecture idea is really cool, but I've got stuck at testing it. Could someone tell me how can I in a readable and easy way test DOM output of a CycleJS component?

I have a Slider component like this:

```javascript
const Slider = ({DOM, props$}) => {
    const initialValue$ = props$.map(props => props.initial).first();
    const newValue$ = DOM.select('.slider').events('input').map(e => e.target.value);
    const value$ = initialValue$.concat(newValue$);

    const vtree$ = Rx.Observable.combineLatest(props$, value$, (props, value) =>
        <div>
            {props.label}: {value} <input className="slider" type="range" min={props.min} max={props.max} value={value}/>
        </div>
    );

    return {
        DOM: vtree$,
        value$
    };
};

export default (sources) => Isolate(Slider)(sources);
```

Then i have a test like this:

```javascript
describe('Slider component', () => {
    it('should update value', () => {
        const props$ = Observable.just({initial: 50});
        const DOM = mockDOMSource({'.slider': {input: Observable.just({target: {value: 5}})}});
        const sinks = Slider({DOM, props$});
        sinks.DOM
            .last()
            .subscribe(vtree => {
                const inputValue = vtree.children[3].properties.value.value;
                inputValue.should.be.equal(5);
            });
    });
});
```

As you can see - searching for the proper element in the VTree is not really intuitive. Are there somewhere tools to make it easy to test, something like in React? I've tried cyclejs-mock, but it's not too elegant and readable imo.

**Comment by staltz** [comment]
@sarneeh, I recommend looking at [this project](https://github.com/futurice/power-ui), it has extensive tests: https://github.com/futurice/power-ui/blob/master/src/components/widgets/DataTable/test.js
It's not updated to the latest versions, but still gives a good idea how to test.
