### ISSUE TITLE
Unnecessary re-isolation in isolateModule

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/core#328]
https://github.com/cyclejs/dom/blob/diversity/src/isolateModule.ts#L74

Here the component is re-isolated even if it's isolating string didn't change. By re-isolating I mean removing an item from `isolatedElements` and then setting it back again.

**Comment by TylorS** [comment]
Yeah, thanks for pointing this out. That's what I get for copy/paste :)

**Comment by staltz** [comment]
Fixed in cycle dom v10.0.4. We can reopen if it persists.
