### ISSUE TITLE
dom transposition seem not to work

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#330]
This shows that transposition doesn't work, it doesn't subscribe to the source, presumably it should.
http://www.webpackbin.com/NJLcpRdNZ

**Comment by staltz** [comment]
In 10.0.0-rc32 yes, it's bugged, I know. Just got bugged mysteriously when upgrading to the xstream with new combine() API. I've been debugging this yesterday and today.

**Comment by staltz** [comment]
Fixed in 10.0.0-rc33
