### ISSUE TITLE
State handling when dealing with routing.

### ISSUE THREAD

**Issue by Cmdv** [cyclejs/core#332]
This is a discussion about what people think is the best approach to handling _state/props stream_ when an app has routing.

It seems this subject is still very much up in the air, even though the solution seems to be a circular-dependency if you want to be able to manually pipe your state throughout the app. (a global state was deemed a top down approach which is not what cycle is after)

The issue I currently have is the  _state stream_ resolves every time you change route. So the next route to use the _state stream_ will be a new stream or visually it will reset if the stream had a `startWith`.

If someone has worked this out then how are they sharing the state between their pages?

**Comment by ntilwalli** [comment]
I've posted example repos demonstrating two different approaches for this.

1. Maintaining state in parent component while injecting into children during routing (https://github.com/ntilwalli/routingWithState)
2. Using pushState to store a state object or state stream and injecting into children during routing
(https://github.com/ntilwalli/routingWithPushState)

Are there any use-cases not covered by these two approaches?

**Comment by Cmdv** [comment]
Superb answers @ntilwalli I'm going to test them out today see if I can find any edge cases.

**Comment by lius** [comment]
I've spotted one: ntilwalli/routingWithState#1

**Comment by ntilwalli** [comment]
@lius Fixed. It was an issue with `http-server` and not the code, I've switched to `live-server` for entry-file support.
