### ISSUE TITLE
DOM: сurrentTarget is lost if processed asynchronously

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/core#334]
http://www.webpackbin.com/NJvwBhgBb

The reason must be the mutation inside EventDelegator. Is it possible to use cloning instead?

**Comment by laszlokorte** [comment]
Does it really make sense to process events async? I mean you could not `preventDefault` or `stopPropagation` and the target event may already be detached from the dom.

In case you really need async event processing you should manually extract the properties you need manually before the delay.

Of cause this should be documented somewhere.

**Comment by Hypnosphi** [comment]
>Does it really make sense to process events async?

Sure it does. The simplest use case is debouncing

**Comment by laszlokorte** [comment]
Sure, but as I said you lose some ways of processing the event anyway: you can not call `preventDefault` etc on the event object. So if you are doing async processing you need to to what you are doing. Even if cycle would automatically clone the whole event (which could decrease performance?) you would need to be aware of the consequences of async event processing.

Your specific case can easily be worked around via:
```
DOM.select(selector).events('click')
    .map((e) => e.currentTarget)
    .compose(delay())
    .debug(t => console.log(`${selector}: ${t.className}`));
```

Even if the event object itself would be cloned, the next person would come by and try:

```
DOM.select(selector).events('click')
    .compose(delay())
    .debug(e => console.log(e.currentTarget.parentNode.parentNode));
```

which may fail if the target is already detached. Or even your exact case may still result in unexpected results if the classList of the element changes during the delay.

So to fully support all cases we would need to to a deep clone of the whole DOM tree for each and every event. This is practically impossible.

**Comment by Hypnosphi** [comment]
Don't we have that as a vtree?

**Comment by laszlokorte** [comment]
The event object is the real DOM event object from the browser. `currentTarget` etc are real DOM nodes with a bunch of information that is not available in the vtree (eg all kind of layout information, pageX, pageY, offsetWidth...)

**Comment by staltz** [comment]
I'll label this as a discussion until/if a consensus is reached that this is a bug and there's a clear task to do.
