### ISSUE TITLE
cycle/http stop requesting after getting 401 error

### ISSUE THREAD

**Issue by kkpoon** [cyclejs/core#337]
I make a simple login as in this gist:
https://gist.github.com/kkpoon/96ea4c5e67a173bf114e0db40750693d

it is works ok when I type correct password, below screen shot shows 3 auth requests sent when pressed 3 times Login button with correct username password

![screen shot 2016-06-24 at 6 15 35 pm](https://cloud.githubusercontent.com/assets/191992/16335152/b0fedc56-3a37-11e6-86fe-48397d4bb475.png)

Once I have input wrong username and password, it received 401 status. and no matter how many times I press the login button with wrong username password, it just sent one request

![screen shot 2016-06-24 at 6 18 16 pm](https://cloud.githubusercontent.com/assets/191992/16335219/1005106c-3a38-11e6-9676-47fc74eba33f.png)

Even I correct the username password to the good one, it does not send any more request to the server.

It looks like `loginRequest$` still producing when I press login, but `loginResult$` does not get any message from the subscription, no HTTP request sent.

**Comment by whitecolor** [comment]
You should correctly handle errors. This:
```js
.mergeAll()
    .catch(err => Rx.Observable.just({error: err}))
```
Will create a flat stream of responses and after the error stream completes, this is how streams work, even if you catch an error. Instead you want to do something like:
```js
.map(r$ => r$.catch(err => just({error: err})))
  .mergeAll()    
```

**Comment by kkpoon** [comment]
thanks @whitecolor . you are correct

I changed the stream to handle the login result to

```js
  const loginResult$ = HTTP
    .filter(res$ => res$.request.name === 'login-auth')
    .map(res$ => res$
      .catch(err => Rx.Observable.just({error: err}))
      .map(res => res.body)
    )
    .mergeAll()
    .startWith(null);
```

**Comment by kkpoon** [comment]
This is not the issue of cycle/http but my concept. Thanks

**Comment by whitecolor** [comment]
this thing https://github.com/whitecolor/cycle-async-driver has helpers `.success()` and `failure()` which provide flat streams, helpers maybe used with official HTTP driver.
