### ISSUE TITLE
Huge file size for simple program?

### ISSUE THREAD

**Issue by mz3** [cyclejs/core#338]
When using browserify + minifyify, the model-view-intent example transpiles to a 224k file

`browserify script.js -o bundle.js -t [ babelify --presets [ es2015 ] ] -d -p [minifyify --map bundle.js.map --output bundle.js.map]`

Even this simple example is more than 200k:

```javascript
import {Observable} from 'rx';
import Cycle from '@cycle/core';
import {div, input, h2, makeDOMDriver} from '@cycle/dom'; // this line alone increases output by 220k

console.log("test");
```

How can we get smaller files sizes? Is it a matter of babel bloating things, or a need for increased modularity?

**Comment by staltz** [comment]
Hi @mz3, that happens for the current stable version of Cycle.js. The next big version will be significantly smaller, we've been working on it for 5 months and we'll release it... next week!
