### ISSUE TITLE
What can be the better way to integrate Service Workers into cycle?

### ISSUE THREAD

**Issue by leiserfg** [cyclejs/core#343]
I want to use that technology for implementing a-la facebook notifications but i don't know where put it on a cycle arch.

**Comment by whitecolor** [comment]
Should be in driver land.

**Comment by leiserfg** [comment]
Yes, but once the page is closed the worker keeps running and it should be capable of send requests to the server and show notifications to the user. It's tightly coupled  to the domain, so should not be part of a driver.

**Comment by TylorS** [comment]
Is there any direction in which the service worker would need to communicate with the application?

**Comment by whitecolor** [comment]
@leiserfg service worker and page have different contexts so communication between them require some intermediate layer (to interchange via messages), this is a good domain for driver. 

If you want you may develop you service worker logic using cycle. So you will have two cycle apps that communicate via driver, I assume this is the most "pure" option.
