### ISSUE TITLE
Selected nodes lost on isolated component after rerender of the view

### ISSUE THREAD

**Issue by kibin** [cyclejs/core#346]
Repro:

```javascript
import {run} from '@cycle/xstream-run'
import {div, button, makeDOMDriver} from '@cycle/dom'
import isolate from '@cycle/isolate'

function main(sources) {
  return {
    DOM: sources.DOM
      .select(`button`)
      .events(`click`)
      .mapTo(1)
      .fold(state => state + 1, 0)
      .map(state =>
        div(`.this-causes-rerender-${state}`, [
          button(`+`),
          state,
        ]),
      ),
  }
}

run(isolate(main), {
  DOM: makeDOMDriver(`#content`),
})
```

Clicks are stopped after reaching 2.

**Comment by TylorS** [comment]
Webpackbin for ease or testing http://www.webpackbin.com/EJUrjQbLW

**Comment by TylorS** [comment]
Thank you @kibin for the report and the test case

**Comment by TylorS** [comment]
@staltz Removing the class name that is always changing on the div gives the 'expected' behavior. My best guess without really digging into this, is that the EventDelegator is not updating the isolated root each time properly.

**Comment by Hypnosphi** [comment]
Snabbdom identifies nodes by selector+key. So if selector changes, node is considered as new. The workaraund is to use `{props: {className}}` instead

**Comment by staltz** [comment]
@Hypnosphi is right. This issue is solved.

**Comment by kibin** [comment]
This issue is not only about dynamic classnames.
What about if you need to show loader instead of a component, while there is a request going on?
That’s the case with the

**Comment by TylorS** [comment]
@kibin Would something like this work for you?

```js
function Components (sources) {
  const someAction$ = sources.DOM.select(...).events(...)
  const request$ = someAction$.mapTo({url: '...'})

  const showLoader$ = xs.merge( request$.mapTo(true), source.HTTP.response$$.mapTo(false) )

  const view$ = showLoader$.map(x => x ? showLoadingPage() : showOtherPage() )

  return {DOM: view$, HTTP: request$}
}
```
